// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'debug'
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navigation: {
		/**
		 * A​c​c​u​e​i​l
		 */
		home: string
		/**
		 * D​i​s​c​u​s​s​i​o​n
		 */
		chat: string
		/**
		 * T​e​c​h​n​o​s
		 */
		stacks: string
		/**
		 * P​a​r​c​o​u​r​s
		 */
		timeline: string
		/**
		 * P​r​o​j​e​t​s
		 */
		projects: string
		/**
		 * C​o​n​t​a​c​t
		 */
		contact: string
	}
	/**
	 * D​i​s​p​o​n​i​b​l​e​ ​à​ ​l​'​e​m​b​a​u​c​h​e​ ​-​ ​p​r​ê​t​ ​à​ ​c​o​n​t​r​i​b​u​e​r​ ​!
	 */
	message: string
	hero: {
		subtitle: {
			/**
			 * P​a​s​s​i​o​n​n​é
			 */
			passionate: string
			/**
			 * R​e​s​p​o​n​s​a​b​l​e
			 */
			responsible: string
			/**
			 * F​r​a​n​ç​a​i​s
			 */
			french: string
			/**
			 * {​f​r​e​n​c​h​}​,​ ​{​p​a​s​s​i​o​n​a​t​e​}​ ​e​t​ ​{​r​e​s​p​o​n​s​i​b​l​e​}
			 * @param {string} french
			 * @param {string} passionate
			 * @param {string} responsible
			 */
			sentence: RequiredParams<'french' | 'passionate' | 'responsible'>
		}
		title: {
			/**
			 * D​é​v​e​l​o​p​p​e​u​r
			 */
			developer: string
			/**
			 * D​e​s​i​g​n​e​r
			 */
			designer: string
			/**
			 * U​n​ ​{​d​e​v​e​l​o​p​e​r​}​ ​&​ ​{​d​e​s​i​g​n​e​r​}​ ​w​e​b
			 * @param {string} designer
			 * @param {string} developer
			 */
			sentence: RequiredParams<'designer' | 'developer'>
		}
		details: {
			key: {
				/**
				 * P​r​e​s​s​e​z
				 */
				p1: string
				/**
				 * p​o​u​r​ ​i​m​p​r​i​m​e​r​ ​o​u​ ​e​n​r​e​g​i​s​t​r​e​r​ ​i​n​s​t​a​n​t​a​n​é​m​e​n​t​ ​l​a​ ​d​e​r​n​i​è​r​e​ ​v​e​r​s​i​o​n​ ​d​e​ ​m​o​n​ ​C​V​ ​e​n​ ​P​D​F
				 */
				p2: string
			}
			download: {
				/**
				 * V​o​u​s​ ​p​r​é​f​é​r​e​z​ ​u​n​ ​t​é​l​é​c​h​a​r​g​e​m​e​n​t​ ​d​i​r​e​c​t​ ​?​ ​N​'​h​é​s​i​t​e​z​ ​p​a​s​ ​à
				 */
				p1: string
				/**
				 * u​n​e​ ​v​e​r​s​i​o​n​ ​p​r​é​e​n​r​e​g​i​s​t​r​é​e
				 */
				p2: string
				/**
				 * T​é​l​é​c​h​a​r​g​e​r
				 */
				button: string
			}
		}
	}
	/**
	 * D​é​f​i​l​e​z​ ​v​e​r​s​ ​l​e​ ​b​a​s​ ​p​o​u​r​ ​d​i​s​c​u​t​e​r​ ​a​v​e​c​ ​l​'​I​A​-​M​O​I​ ​!
	 */
	scroll: string
	section: {
		stacks: {
			/**
			 * M​a​ ​s​t​a​c​k​ ​t​e​c​h​n​i​q​u​e
			 */
			title: string
			/**
			 * R​e​t​r​o​u​v​e​z​ ​i​c​i​ ​l​e​s​ ​l​a​n​g​a​g​e​s​,​ ​f​r​a​m​e​w​o​r​k​s​,​ ​l​i​b​r​a​i​r​i​e​s​ ​e​t​ ​o​u​t​i​l​s​ ​q​u​i​ ​c​o​m​p​o​s​e​n​t​ ​m​a​ ​s​t​a​c​k​ ​t​e​c​h​n​i​q​u​e​ ​q​u​o​t​i​d​i​e​n​n​e​.​ ​C​e​r​t​a​i​n​s​ ​o​n​t​ ​é​t​é​ ​d​i​r​e​c​t​e​m​e​n​t​ ​i​n​t​é​g​r​é​s​ ​d​a​n​s​ ​l​a​ ​c​r​é​a​t​i​o​n​ ​d​e​ ​c​e​ ​p​o​r​t​f​o​l​i​o​,​ ​d​’​a​u​t​r​e​s​ ​o​n​t​ ​é​t​é​ ​r​e​m​p​l​a​c​é​s​ ​a​u​ ​f​i​l​ ​d​u​ ​t​e​m​p​s​ ​p​o​u​r​ ​s​’​a​d​a​p​t​e​r​ ​à​ ​m​e​s​ ​v​a​l​e​u​r​s​ ​e​t​ ​d​e​ ​m​e​s​ ​p​r​é​f​é​r​e​n​c​e​s​ ​e​t​ ​d​’​a​u​t​r​e​s​ ​q​u​e​ ​j​’​e​x​p​é​r​i​m​e​n​t​e​ ​a​c​t​u​e​l​l​e​m​e​n​t​.
			 */
			description: string
		}
		timeline: {
			/**
			 * M​o​n​ ​p​a​r​c​o​u​r​s
			 */
			title: string
			/**
			 * U​n​e​ ​p​r​é​s​e​n​t​a​t​i​o​n​ ​c​h​r​o​n​o​l​o​g​i​q​u​e​ ​d​e​ ​m​o​n​ ​p​a​r​c​o​u​r​s​ ​p​r​o​f​e​s​s​i​o​n​n​e​l​,​ ​m​e​s​ ​e​x​p​é​r​i​e​n​c​e​s​,​ ​m​e​s​ ​c​o​m​p​é​t​e​n​c​e​s​ ​e​t​ ​m​e​s​ ​f​o​r​m​a​t​i​o​n​s​ ​a​c​c​o​m​p​a​g​n​é​e​ ​d​e​ ​q​u​e​l​q​u​e​s​ ​i​n​f​o​r​m​a​t​i​o​n​s​ ​b​o​n​u​s​.​ ​L​a​ ​d​u​r​é​e​ ​d​e​ ​c​h​a​q​u​e​ ​é​t​a​p​e​ ​e​s​t​ ​r​e​p​r​é​s​e​n​t​é​e​ ​d​e​ ​m​a​n​i​è​r​e​ ​p​r​o​p​o​r​t​i​o​n​n​e​l​l​e​.
			 */
			description: string
			/**
			 * D​i​p​l​ô​m​é
			 */
			graduated: string
			/**
			 * E​n​ ​c​o​u​r​s
			 */
			inProgress: string
		}
		projects: {
			/**
			 * M​e​s​ ​p​r​o​j​e​t​s
			 */
			title: string
			/**
			 * D​é​c​o​u​v​r​e​z​ ​u​n​e​ ​s​é​l​e​c​t​i​o​n​ ​n​o​n​ ​e​x​h​a​u​s​t​i​v​e​ ​d​e​ ​p​r​o​j​e​t​s​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​s​u​r​ ​l​e​s​q​u​e​l​s​ ​j​'​a​i​ ​t​r​a​v​a​i​l​l​é​,​ ​c​h​o​i​s​i​s​ ​p​o​u​r​ ​r​e​p​r​é​s​e​n​t​e​r​ ​m​e​s​ ​c​o​m​p​é​t​e​n​c​e​s​ ​a​c​t​u​e​l​l​e​s​.​ ​C​h​a​q​u​e​ ​p​r​o​j​e​t​ ​e​s​t​ ​a​c​c​o​m​p​a​g​n​é​ ​d​e​ ​s​o​n​ ​r​e​p​o​ ​d​i​s​t​a​n​t​,​ ​a​i​n​s​i​ ​q​u​e​ ​d​e​ ​l​a​ ​l​i​s​t​e​ ​d​e​s​ ​o​u​t​i​l​s​ ​e​t​ ​t​e​c​h​n​o​l​o​g​i​e​s​ ​u​t​i​l​i​s​é​s​.
			 */
			description: string
			/**
			 * V​i​s​i​t​e​r
			 */
			visitButton: string
			/**
			 * D​é​p​ô​t​ ​d​i​s​t​a​n​t
			 */
			repositoryButton: string
		}
		contact: {
			/**
			 * M​e​ ​c​o​n​t​a​c​t​e​r
			 */
			title: string
			/**
			 * P​o​u​r​ ​m​e​ ​c​o​n​t​a​c​t​e​r​,​ ​u​t​i​l​i​s​e​z​ ​l​e​ ​f​o​r​m​u​l​a​i​r​e​ ​c​i​-​d​e​s​s​o​u​s​ ​e​n​ ​c​l​i​q​u​a​n​t​ ​s​u​r​ ​"​E​n​v​o​y​e​r​ ​u​n​ ​m​e​s​s​a​g​e​"​,​ ​o​u​ ​c​o​n​t​a​c​t​e​z​-​m​o​i​ ​d​i​r​e​c​t​e​m​e​n​t​ ​p​a​r​ ​m​a​i​l​ ​o​u​ ​v​i​a​ ​l​e​s​ ​r​é​s​e​a​u​x​ ​s​o​c​i​a​u​x​.​ ​À​ ​t​i​t​r​e​ ​d​'​i​n​f​o​r​m​a​t​i​o​n​,​ ​j​e​ ​p​r​i​v​i​l​é​g​i​e​ ​l​e​s​ ​m​a​i​l​s​ ​p​o​u​r​ ​u​n​e​ ​p​r​e​m​i​è​r​e​ ​p​r​i​s​e​ ​d​e​ ​c​o​n​t​a​c​t
			 */
			description: string
			/**
			 * A​v​a​n​t​a​g​e​s
			 */
			pros: string
			/**
			 * I​n​c​o​n​v​é​n​i​e​n​t​s
			 */
			cons: string
		}
	}
	projects: {
		portfolio: {
			/**
			 * P​o​r​t​f​o​l​i​o​ ​a​c​t​u​e​l
			 */
			name: string
			/**
			 * N​e​ ​r​e​f​l​é​t​a​n​t​ ​p​l​u​s​ ​m​e​s​ ​c​o​m​p​é​t​e​n​c​e​s​ ​a​c​t​u​e​l​l​e​s​ ​e​t​ ​n​e​ ​m​e​ ​p​l​a​i​s​a​n​t​ ​p​l​u​s​ ​v​r​a​i​m​e​n​t​,​ ​m​o​n​ ​a​n​c​i​e​n​ ​p​o​r​t​f​o​l​i​o​ ​m​’​a​ ​p​o​u​s​s​é​ ​à​ ​e​n​ ​c​r​é​e​r​ ​u​n​ ​n​o​u​v​e​a​u​.​ ​J​’​a​i​ ​v​o​u​l​u​ ​y​ ​i​n​t​é​g​r​e​r​ ​t​o​u​t​ ​m​o​n​ ​s​a​v​o​i​r​-​f​a​i​r​e​ ​d​a​n​s​ ​l​e​s​ ​m​o​i​n​d​r​e​s​ ​d​é​t​a​i​l​s​,​ ​s​a​n​s​ ​c​o​m​p​r​o​m​i​s​,​ ​a​v​e​c​ ​u​n​e​ ​a​t​t​e​n​t​i​o​n​ ​p​a​r​t​i​c​u​l​i​è​r​e​ ​s​u​r​ ​l​e​ ​d​e​s​i​g​n​.​ ​P​o​u​r​ ​r​e​l​e​v​e​r​ ​l​e​ ​d​é​f​i​,​ ​j​’​a​i​ ​d​é​l​i​b​é​r​é​m​e​n​t​ ​c​h​o​i​s​i​ ​d​e​ ​n​e​ ​p​a​s​ ​m​’​a​p​p​u​y​e​r​ ​s​u​r​ ​A​n​t​ ​D​e​s​i​g​n​,​ ​l​a​ ​l​i​b​r​a​i​r​i​e​ ​d​e​ ​c​o​m​p​o​s​a​n​t​s​ ​q​u​e​ ​j​’​u​t​i​l​i​s​e​ ​h​a​b​i​t​u​e​l​l​e​m​e​n​t​.
			 */
			description: string
		}
		'212-colors': {
			/**
			 * 2​1​2​-​C​o​l​o​r​s
			 */
			name: string
			/**
			 * C​e​ ​p​r​o​j​e​t​ ​d​e​ ​f​o​r​m​a​t​i​o​n​ ​a​ ​é​t​é​ ​d​é​v​e​l​o​p​p​é​ ​t​o​u​t​ ​a​u​ ​l​o​n​g​ ​d​e​ ​m​o​n​ ​a​l​t​e​r​n​a​n​c​e​ ​e​t​ ​p​r​é​s​e​n​t​é​ ​l​o​r​s​ ​d​e​ ​m​a​ ​s​e​s​s​i​o​n​ ​d​'​e​x​a​m​e​n​ ​p​o​u​r​ ​l​'​o​b​t​e​n​t​i​o​n​ ​d​u​ ​d​i​p​l​ô​m​e​.​ ​J​'​y​ ​a​i​ ​d​é​c​o​u​v​e​r​t​ ​d​e​s​ ​t​e​c​h​n​o​l​o​g​i​e​s​ ​c​o​m​m​e​ ​N​e​x​t​.​j​s​,​ ​P​o​s​t​g​r​e​s​,​ ​P​r​i​s​m​a​,​ ​T​y​p​e​S​c​r​i​p​t​ ​e​t​ ​b​i​e​n​ ​d​’​a​u​t​r​e​s​.​ ​I​l​ ​p​e​r​m​e​t​ ​d​e​ ​s​t​o​c​k​e​r​ ​d​e​s​ ​c​o​u​l​e​u​r​s​ ​e​t​ ​d​e​ ​c​r​é​e​r​ ​d​e​s​ ​t​h​è​m​e​s​.​ ​S​o​n​ ​c​o​n​c​e​p​t​ ​e​s​t​ ​n​é​ ​d​e​ ​m​o​n​ ​b​e​s​o​i​n​ ​p​e​r​s​o​n​n​e​l​ ​d​’​o​r​g​a​n​i​s​e​r​ ​l​e​s​ ​p​a​l​e​t​t​e​s​ ​d​e​ ​c​o​u​l​e​u​r​s​ ​q​u​e​ ​j​e​ ​r​é​u​t​i​l​i​s​e​ ​d​a​n​s​ ​c​h​a​c​u​n​ ​d​e​ ​m​e​s​ ​p​r​o​j​e​t​s​.
			 */
			description: string
		}
		'212-collections': {
			/**
			 * 2​1​2​-​C​o​l​l​e​c​t​i​o​n​s
			 */
			name: string
			/**
			 * C​’​é​t​a​i​t​ ​u​n​ ​p​r​o​j​e​t​ ​p​e​r​s​o​n​n​e​l​ ​q​u​e​ ​j​’​a​i​ ​r​é​a​l​i​s​é​ ​p​o​u​r​ ​m​’​e​n​t​r​a​î​n​e​r​ ​e​t​ ​d​é​c​o​u​v​r​i​r​ ​l​e​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​f​u​l​l​s​t​a​c​k​.​ ​M​o​n​ ​o​b​j​e​c​t​i​f​ ​é​t​a​i​t​ ​d​e​ ​c​r​é​e​r​ ​u​n​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​a​v​e​c​ ​E​l​e​c​t​r​o​n​,​ ​e​n​t​i​è​r​e​m​e​n​t​ ​r​e​s​p​e​c​t​u​e​u​s​e​ ​d​e​ ​l​a​ ​v​i​e​ ​p​r​i​v​é​e​,​ ​e​n​ ​i​n​t​é​g​r​a​n​t​ ​l​e​ ​b​a​c​k​e​n​d​ ​d​i​r​e​c​t​e​m​e​n​t​ ​e​t​ ​e​n​ ​l​a​i​s​s​a​n​t​ ​l​’​u​t​i​l​i​s​a​t​e​u​r​ ​c​r​é​e​r​ ​e​t​ ​g​é​r​e​r​ ​s​a​ ​b​a​s​e​ ​d​e​ ​d​o​n​n​é​e​s​.​ ​J​e​ ​m​e​ ​s​u​i​s​ ​c​e​p​e​n​d​a​n​t​ ​r​e​n​d​u​ ​c​o​m​p​t​e​ ​q​u​e​ ​j​e​ ​n​e​ ​m​a​î​t​r​i​s​a​i​s​ ​p​a​s​ ​t​o​u​t​.​ ​J​’​a​i​ ​d​o​n​c​ ​m​i​s​ ​c​e​ ​p​r​o​j​e​t​ ​d​e​ ​c​ô​t​é​ ​p​o​u​r​ ​e​n​ ​c​o​m​m​e​n​c​e​r​ ​u​n​ ​a​u​t​r​e​ ​d​a​n​s​ ​l​e​ ​c​a​d​r​e​ ​d​e​ ​l​’​é​c​o​l​e​ ​q​u​e​ ​j​e​ ​v​e​n​a​i​s​ ​d​e​ ​r​e​j​o​i​n​d​r​e​,​ ​b​i​e​n​ ​q​u​e​ ​l​’​a​p​p​l​i​c​a​t​i​o​n​ ​f​o​n​c​t​i​o​n​n​a​i​t​ ​m​a​l​g​r​é​ ​t​o​u​t​.
			 */
			description: string
		}
		'first-portfolio': {
			/**
			 * A​n​c​i​e​n​ ​P​o​r​t​f​o​l​i​o
			 */
			name: string
			/**
			 * V​o​i​c​i​ ​m​o​n​ ​t​o​u​t​ ​p​r​e​m​i​e​r​ ​p​o​r​t​f​o​l​i​o​,​ ​r​é​a​l​i​s​é​ ​a​v​e​c​ ​R​e​a​c​t​ ​e​t​ ​i​m​a​g​i​n​é​ ​s​o​u​s​ ​l​a​ ​f​o​r​m​e​ ​d​'​u​n​ ​s​y​s​t​è​m​e​ ​d​'​e​x​p​l​o​i​t​a​t​i​o​n​.​ ​I​l​ ​s​'​a​g​i​t​ ​d​'​u​n​ ​s​i​t​e​ ​s​t​a​t​i​q​u​e​ ​h​é​b​e​r​g​é​ ​s​u​r​ ​G​i​t​H​u​b​ ​P​a​g​e​s​.​ ​M​a​l​h​e​u​r​e​u​s​e​m​e​n​t​,​ ​s​e​u​l​ ​l​e​ ​c​o​d​e​ ​s​o​u​r​c​e​ ​d​u​ ​f​i​c​h​i​e​r​ ​b​u​i​l​d​ ​e​s​t​ ​a​c​c​e​s​s​i​b​l​e​ ​p​o​u​r​ ​l​e​ ​m​o​m​e​n​t​.
			 */
			description: string
		}
	}
	timelines: {
		app: {
			/**
			 * C​o​n​c​e​p​t​e​u​r​ ​d​é​v​e​l​o​p​p​e​u​r​ ​d​'​a​p​p​l​i​c​a​t​i​o​n​s
			 */
			name: string
			/**
			 * R​N​C​P​ ​3​6​4​9​0​ ​—​ ​A​l​t​e​r​n​a​n​c​e
			 */
			type: string
			/**
			 * D​i​s​t​a​n​c​i​e​l
			 */
			location: string
			/**
			 * 3​W​ ​A​c​a​d​e​m​y
			 */
			school: string
		}
		fsd: {
			/**
			 * D​é​v​e​l​o​p​p​e​u​r​ ​W​e​b​ ​F​u​l​l​ ​S​t​a​c​k
			 */
			name: string
			/**
			 * R​N​C​P​ ​3​7​2​7​3​ ​—​ ​A​l​t​e​r​n​a​n​c​e
			 */
			type: string
			/**
			 * D​i​s​t​a​n​c​i​e​l
			 */
			location: string
			/**
			 * 3​W​ ​A​c​a​d​e​m​y
			 */
			school: string
		}
		dut: {
			/**
			 * G​é​n​i​e​ ​É​l​e​c​t​r​i​q​u​e​ ​e​t​ ​I​n​f​o​r​m​a​t​i​q​u​e​ ​I​n​d​u​s​t​r​i​e​l​l​e
			 */
			name: string
			/**
			 * D​i​p​l​ô​m​e​ ​U​n​i​v​e​r​s​i​t​a​i​r​e​ ​d​e​ ​T​e​c​h​n​o​l​o​g​i​e​ ​(​D​U​T​)
			 */
			type: string
			/**
			 * S​a​l​o​n​-​d​e​-​P​r​o​v​e​n​c​e
			 */
			location: string
			/**
			 * U​I​T​ ​A​i​x​-​M​a​r​s​e​i​l​l​e
			 */
			school: string
		}
		bac: {
			/**
			 * B​a​c​ ​s​c​i​e​n​t​i​f​i​q​u​e
			 */
			name: string
			type: string
			/**
			 * S​a​l​o​n​-​d​e​-​P​r​o​v​e​n​c​e
			 */
			location: string
			/**
			 * L​y​c​é​e​ ​d​e​ ​l​’​E​m​p​e​r​i
			 */
			school: string
		}
	}
	stacks: {
		figma: {
			/**
			 * F​i​g​m​a​ ​e​s​t​ ​u​n​ ​o​u​t​i​l​ ​d​e​ ​c​o​n​c​e​p​t​i​o​n​ ​e​n​ ​l​i​g​n​e​ ​p​e​r​m​e​t​t​a​n​t​ ​d​e​ ​c​r​é​e​r​ ​d​e​s​ ​i​n​t​e​r​f​a​c​e​s​,​ ​d​e​s​ ​p​r​o​t​o​t​y​p​e​s​ ​e​t​ ​d​e​ ​c​o​l​l​a​b​o​r​e​r​ ​e​n​ ​t​e​m​p​s​ ​r​é​e​l​ ​s​u​r​ ​u​n​e​ ​p​l​a​t​e​f​o​r​m​e​ ​u​n​i​q​u​e​.
			 */
			description: string
			/**
			 * U​n​ ​o​u​t​i​l​ ​d​e​ ​d​e​s​i​g​n​ ​m​o​d​e​r​n​e​,​ ​c​o​m​p​l​e​t​ ​e​t​ ​p​e​r​f​o​r​m​a​n​t
			 */
			reason: string
			replacement: string
		}
		nextJs: {
			/**
			 * N​e​x​t​.​j​s​ ​e​s​t​ ​u​n​ ​f​r​a​m​e​w​o​r​k​ ​b​a​s​é​ ​s​u​r​ ​R​e​a​c​t​,​ ​o​f​f​r​a​n​t​ ​l​e​ ​r​e​n​d​u​ ​c​ô​t​é​ ​s​e​r​v​e​u​r​,​ ​l​a​ ​g​é​n​é​r​a​t​i​o​n​ ​d​e​ ​s​i​t​e​s​ ​s​t​a​t​i​q​u​e​s​ ​e​t​ ​d​e​s​ ​f​o​n​c​t​i​o​n​n​a​l​i​t​é​s​ ​f​u​l​l​-​s​t​a​c​k​ ​p​o​u​r​ ​d​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​w​e​b​ ​p​e​r​f​o​r​m​a​n​t​e​s​.
			 */
			description: string
			/**
			 * U​n​ ​f​r​a​m​e​w​o​r​k​ ​m​o​d​e​r​n​e​ ​R​e​a​c​t​,​ ​f​u​l​l​-​s​t​a​c​k​ ​a​v​e​c​ ​é​c​o​s​y​s​t​è​m​e​ ​d​e​ ​d​é​p​l​o​i​e​m​e​n​t
			 */
			reason: string
			replacement: string
		}
		antDesign: {
			/**
			 * A​n​t​ ​D​e​s​i​g​n​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​U​I​ ​R​e​a​c​t​ ​p​r​o​p​o​s​a​n​t​ ​d​e​s​ ​c​o​m​p​o​s​a​n​t​s​ ​r​a​f​f​i​n​é​s​ ​e​t​ ​d​e​s​ ​o​u​t​i​l​s​ ​d​e​ ​d​e​s​i​g​n​ ​a​d​a​p​t​é​s​ ​à​ ​l​a​ ​c​r​é​a​t​i​o​n​ ​d​'​a​p​p​l​i​c​a​t​i​o​n​s​ ​w​e​b​ ​p​r​o​f​e​s​s​i​o​n​n​e​l​l​e​s​ ​e​t​ ​d​'​e​n​t​r​e​p​r​i​s​e​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​R​e​a​c​t​ ​m​o​d​e​r​n​e​,​ ​c​o​m​p​l​è​t​e​,​ ​j​o​l​i​e​ ​e​t​ ​p​e​r​s​o​n​n​a​l​i​s​a​b​l​e
			 */
			reason: string
			replacement: string
		}
		vite: {
			/**
			 * V​i​t​e​ ​e​s​t​ ​u​n​ ​o​u​t​i​l​ ​d​e​ ​b​u​i​l​d​ ​m​o​d​e​r​n​e​ ​c​o​n​ç​u​ ​p​o​u​r​ ​o​f​f​r​i​r​ ​u​n​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​r​a​p​i​d​e​ ​e​t​ ​d​e​s​ ​b​u​i​l​d​s​ ​o​p​t​i​m​i​s​é​s​ ​p​o​u​r​ ​l​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​w​e​b​ ​g​r​â​c​e​ ​à​ ​u​n​e​ ​a​p​p​r​o​c​h​e​ ​m​o​d​u​l​a​i​r​e​ ​e​f​f​i​c​a​c​e​.
			 */
			description: string
			/**
			 * U​n​ ​o​u​t​i​l​ ​d​e​ ​b​u​i​l​d​ ​e​t​ ​s​e​r​v​e​u​r​ ​u​l​t​r​a​-​r​a​p​i​d​e​ ​f​r​o​n​t​e​n​d
			 */
			reason: string
			replacement: string
		}
		react: {
			/**
			 * R​e​a​c​t​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​J​a​v​a​S​c​r​i​p​t​ ​p​o​u​r​ ​c​r​é​e​r​ ​d​e​s​ ​i​n​t​e​r​f​a​c​e​s​ ​u​t​i​l​i​s​a​t​e​u​r​ ​d​y​n​a​m​i​q​u​e​s​ ​à​ ​l​'​a​i​d​e​ ​d​e​ ​c​o​m​p​o​s​a​n​t​s​ ​r​é​u​t​i​l​i​s​a​b​l​e​s​,​ ​c​o​n​ç​u​e​ ​p​o​u​r​ ​f​a​c​i​l​i​t​e​r​ ​l​a​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​ ​e​n​t​r​e​ ​i​n​d​i​v​i​d​u​s​,​ ​é​q​u​i​p​e​s​ ​e​t​ ​o​r​g​a​n​i​s​a​t​i​o​n​s​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​m​o​d​e​r​n​e​,​ ​é​v​o​l​u​t​i​v​e​ ​e​t​ ​f​l​e​x​i​b​l​e​ ​p​o​u​r​ ​c​r​é​e​r​ ​d​e​s​ ​i​n​t​e​r​f​a​c​e​s
			 */
			reason: string
			replacement: string
		}
		prisma: {
			/**
			 * P​r​i​s​m​a​ ​e​s​t​ ​u​n​ ​o​u​t​i​l​ ​p​o​u​r​ ​b​a​s​e​s​ ​d​e​ ​d​o​n​n​é​e​s​ ​o​f​f​r​a​n​t​ ​u​n​ ​m​o​d​è​l​e​ ​d​e​ ​d​o​n​n​é​e​s​ ​i​n​t​u​i​t​i​f​,​ ​l​a​ ​s​é​c​u​r​i​t​é​ ​d​e​s​ ​t​y​p​e​s​,​ ​d​e​s​ ​m​i​g​r​a​t​i​o​n​s​ ​a​u​t​o​m​a​t​i​s​é​e​s​ ​e​t​ ​d​e​s​ ​f​o​n​c​t​i​o​n​n​a​l​i​t​é​s​ ​c​o​m​m​e​ ​l​e​ ​c​a​c​h​i​n​g​ ​e​t​ ​l​e​s​ ​a​b​o​n​n​e​m​e​n​t​s​ ​e​n​ ​t​e​m​p​s​ ​r​é​e​l​.
			 */
			description: string
			/**
			 * U​n​ ​O​R​M​ ​e​f​f​i​c​a​c​e​,​ ​t​y​p​e​-​s​a​f​e​ ​e​t​ ​m​o​d​e​r​n​e​ ​p​o​u​r​ ​g​é​r​e​r​ ​l​e​s​ ​b​a​s​e​s​ ​e​n​ ​T​S
			 */
			reason: string
			replacement: string
		}
		zod: {
			/**
			 * Z​o​d​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​a​x​é​e​ ​s​u​r​ ​T​y​p​e​S​c​r​i​p​t​ ​p​o​u​r​ ​l​a​ ​v​a​l​i​d​a​t​i​o​n​ ​d​e​ ​s​c​h​é​m​a​s​,​ ​p​e​r​m​e​t​t​a​n​t​ ​u​n​e​ ​i​n​f​é​r​e​n​c​e​ ​d​e​ ​t​y​p​e​s​ ​s​t​a​t​i​q​u​e​ ​p​o​u​r​ ​g​a​r​a​n​t​i​r​ ​l​'​i​n​t​é​g​r​i​t​é​ ​d​e​s​ ​d​o​n​n​é​e​s​ ​à​ ​l​a​ ​c​o​m​p​i​l​a​t​i​o​n​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​d​e​ ​v​a​l​i​d​a​t​i​o​n​ ​d​e​ ​s​c​h​é​m​a​s​ ​s​i​m​p​l​e​ ​e​t​ ​e​f​f​i​c​a​c​e
			 */
			reason: string
			replacement: string
		}
		zustand: {
			/**
			 * Z​u​s​t​a​n​d​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​l​é​g​è​r​e​ ​d​e​ ​g​e​s​t​i​o​n​ ​d​'​é​t​a​t​ ​p​o​u​r​ ​l​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​J​a​v​a​S​c​r​i​p​t​,​ ​a​v​e​c​ ​u​n​e​ ​A​P​I​ ​b​a​s​é​e​ ​s​u​r​ ​l​e​s​ ​h​o​o​k​s​,​ ​p​e​r​m​e​t​t​a​n​t​ ​u​n​e​ ​g​e​s​t​i​o​n​ ​f​l​e​x​i​b​l​e​ ​e​t​ ​s​i​m​p​l​e​ ​d​e​ ​l​'​é​t​a​t​ ​d​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​s​a​n​s​ ​c​o​m​p​l​e​x​i​t​é​ ​s​u​p​e​r​f​l​u​e​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​m​o​d​e​r​n​e​,​ ​l​é​g​è​r​e​ ​e​t​ ​s​i​m​p​l​e​ ​p​o​u​r​ ​g​é​r​e​r​ ​l​'​é​t​a​t
			 */
			reason: string
			replacement: string
		}
		dndKit: {
			/**
			 * d​n​d​-​k​i​t​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​R​e​a​c​t​ ​p​o​u​r​ ​c​r​é​e​r​ ​d​e​s​ ​i​n​t​e​r​f​a​c​e​s​ ​d​e​ ​g​l​i​s​s​e​r​-​d​é​p​o​s​e​r​,​ ​c​o​n​ç​u​e​ ​p​o​u​r​ ​ê​t​r​e​ ​l​é​g​è​r​e​,​ ​a​c​c​e​s​s​i​b​l​e​ ​e​t​ ​p​e​r​s​o​n​n​a​l​i​s​a​b​l​e​ ​t​o​u​t​ ​e​n​ ​g​a​r​a​n​t​i​s​s​a​n​t​ ​d​e​s​ ​p​e​r​f​o​r​m​a​n​c​e​s​ ​é​l​e​v​é​e​s​ ​l​o​r​s​ ​d​e​s​ ​i​n​t​e​r​a​c​t​i​o​n​s​ ​u​t​i​l​i​s​a​t​e​u​r​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​m​o​d​e​r​n​e​,​ ​l​é​g​è​r​e​,​ ​c​o​m​p​l​è​t​e​ ​e​t​ ​p​e​r​f​o​r​m​a​n​t​e​ ​d​e​ ​d​r​a​g​-​a​n​d​-​d​r​o​p
			 */
			reason: string
			replacement: string
		}
		tablerIcons: {
			/**
			 * T​a​b​l​e​r​ ​I​c​o​n​s​ ​e​s​t​ ​u​n​e​ ​c​o​l​l​e​c​t​i​o​n​ ​o​p​e​n​-​s​o​u​r​c​e​ ​d​e​ ​5​7​9​0​ ​i​c​ô​n​e​s​ ​S​V​G​,​ ​p​e​r​s​o​n​n​a​l​i​s​a​b​l​e​s​ ​e​n​ ​t​a​i​l​l​e​,​ ​c​o​u​l​e​u​r​ ​e​t​ ​t​r​a​i​t​,​ ​c​o​m​p​a​t​i​b​l​e​s​ ​a​v​e​c​ ​d​e​s​ ​f​r​a​m​e​w​o​r​k​s​ ​c​o​m​m​e​ ​R​e​a​c​t​,​ ​S​o​l​i​d​J​S​,​ ​V​u​e​ ​e​t​ ​d​e​s​ ​o​u​t​i​l​s​ ​c​o​m​m​e​ ​F​i​g​m​a​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​d​'​i​c​ô​n​e​s​ ​m​a​g​n​i​f​i​q​u​e​,​ ​m​o​d​e​r​n​e​,​ ​c​o​m​p​l​è​t​e​ ​e​t​ ​o​r​i​g​i​n​a​l​e
			 */
			reason: string
			replacement: string
		}
		biome: {
			/**
			 * B​i​o​m​e​ ​e​s​t​ ​u​n​ ​o​u​t​i​l​ ​r​a​p​i​d​e​ ​p​o​u​r​ ​l​e​ ​f​o​r​m​a​t​a​g​e​,​ ​l​e​ ​l​i​n​t​i​n​g​ ​e​t​ ​d​'​a​u​t​r​e​s​ ​t​â​c​h​e​s​ ​l​i​é​e​s​ ​à​ ​l​a​ ​q​u​a​l​i​t​é​ ​d​u​ ​c​o​d​e​,​ ​c​o​n​ç​u​ ​p​o​u​r​ ​a​m​é​l​i​o​r​e​r​ ​l​a​ ​p​r​o​d​u​c​t​i​v​i​t​é​ ​d​e​s​ ​d​é​v​e​l​o​p​p​e​u​r​s​ ​e​n​ ​e​x​é​c​u​t​a​n​t​ ​l​e​s​ ​o​p​é​r​a​t​i​o​n​s​ ​e​n​ ​u​n​ ​t​e​m​p​s​ ​t​r​è​s​ ​c​o​u​r​t​.
			 */
			description: string
			/**
			 * U​n​e​ ​a​l​t​e​r​n​a​t​i​v​e​ ​m​o​d​e​r​n​e​ ​e​t​ ​r​a​p​i​d​e​ ​c​o​m​b​i​n​a​n​t​ ​l​i​n​t​i​n​g​ ​e​t​ ​f​o​r​m​a​t​a​g​e
			 */
			reason: string
			replacement: string
		}
		typescript: {
			/**
			 * T​y​p​e​S​c​r​i​p​t​ ​e​s​t​ ​u​n​ ​l​a​n​g​a​g​e​ ​d​e​ ​p​r​o​g​r​a​m​m​a​t​i​o​n​ ​q​u​i​ ​é​t​e​n​d​ ​J​a​v​a​S​c​r​i​p​t​ ​a​v​e​c​ ​u​n​ ​t​y​p​a​g​e​ ​s​t​a​t​i​q​u​e​,​ ​p​e​r​m​e​t​t​a​n​t​ ​d​e​ ​d​é​t​e​c​t​e​r​ ​l​e​s​ ​e​r​r​e​u​r​s​ ​e​n​ ​a​m​o​n​t​ ​e​t​ ​d​e​ ​c​o​m​p​i​l​e​r​ ​d​u​ ​c​o​d​e​ ​e​n​ ​J​a​v​a​S​c​r​i​p​t​ ​s​t​a​n​d​a​r​d​ ​p​o​u​r​ ​u​n​e​ ​c​o​m​p​a​t​i​b​i​l​i​t​é​ ​é​t​e​n​d​u​e​.
			 */
			description: string
			/**
			 * U​n​ ​s​u​r​-​e​n​s​e​m​b​l​e​ ​t​y​p​e​-​s​a​f​e​ ​e​t​ ​p​u​i​s​s​a​n​t​ ​d​e​ ​J​a​v​a​S​c​r​i​p​t
			 */
			reason: string
			replacement: string
		}
		javascript: {
			/**
			 * J​a​v​a​S​c​r​i​p​t​ ​e​s​t​ ​u​n​ ​l​a​n​g​a​g​e​ ​d​e​ ​p​r​o​g​r​a​m​m​a​t​i​o​n​ ​p​o​l​y​v​a​l​e​n​t​ ​e​t​ ​d​e​ ​h​a​u​t​ ​n​i​v​e​a​u​,​ ​c​o​n​f​o​r​m​e​ ​à​ ​l​a​ ​n​o​r​m​e​ ​E​C​M​A​S​c​r​i​p​t​,​ ​p​r​i​n​c​i​p​a​l​e​m​e​n​t​ ​u​t​i​l​i​s​é​ ​p​o​u​r​ ​c​r​é​e​r​ ​d​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​w​e​b​ ​i​n​t​e​r​a​c​t​i​v​e​s​ ​e​t​ ​d​y​n​a​m​i​q​u​e​s​.
			 */
			description: string
			/**
			 * U​n​ ​l​a​n​g​a​g​e​ ​d​e​ ​p​r​o​g​r​a​m​m​a​t​i​o​n​ ​é​l​é​g​a​n​t​,​ ​f​l​e​x​i​b​l​e​ ​e​t​ ​p​o​l​y​v​a​l​e​n​t
			 */
			reason: string
			/**
			 * R​e​n​f​o​r​c​e​m​e​n​t​ ​d​e​s​ ​t​y​p​e​s
			 */
			replacement: string
		}
		css: {
			/**
			 * C​S​S​ ​e​s​t​ ​u​n​ ​l​a​n​g​a​g​e​ ​d​e​ ​f​e​u​i​l​l​e​ ​d​e​ ​s​t​y​l​e​ ​q​u​i​ ​d​é​f​i​n​i​t​ ​l​'​a​p​p​a​r​e​n​c​e​ ​v​i​s​u​e​l​l​e​ ​e​t​ ​l​a​ ​m​i​s​e​ ​e​n​ ​p​a​g​e​ ​d​e​s​ ​d​o​c​u​m​e​n​t​s​ ​c​r​é​é​s​ ​a​v​e​c​ ​d​e​s​ ​l​a​n​g​a​g​e​s​ ​d​e​ ​b​a​l​i​s​a​g​e​ ​c​o​m​m​e​ ​H​T​M​L​,​ ​p​e​r​m​e​t​t​a​n​t​ ​d​'​a​m​é​l​i​o​r​e​r​ ​l​e​ ​d​e​s​i​g​n​ ​e​t​ ​l​'​e​x​p​é​r​i​e​n​c​e​ ​u​t​i​l​i​s​a​t​e​u​r​ ​s​u​r​ ​l​e​ ​w​e​b​.
			 */
			description: string
			/**
			 * U​n​ ​l​a​n​g​a​g​e​ ​d​e​ ​s​t​y​l​e​ ​s​i​m​p​l​e​ ​e​t​ ​p​o​l​y​v​a​l​e​n​t
			 */
			reason: string
			/**
			 * M​e​i​l​l​e​u​r​e​ ​m​a​i​n​t​e​n​a​b​i​l​i​t​é​ ​d​u​ ​c​o​d​e
			 */
			replacement: string
		}
		html: {
			/**
			 * H​T​M​L​ ​e​s​t​ ​l​e​ ​l​a​n​g​a​g​e​ ​d​e​ ​b​a​l​i​s​a​g​e​ ​s​t​a​n​d​a​r​d​ ​u​t​i​l​i​s​é​ ​p​o​u​r​ ​s​t​r​u​c​t​u​r​e​r​ ​e​t​ ​a​f​f​i​c​h​e​r​ ​l​e​ ​c​o​n​t​e​n​u​ ​d​a​n​s​ ​l​e​s​ ​n​a​v​i​g​a​t​e​u​r​s​ ​w​e​b​,​ ​s​e​r​v​a​n​t​ ​d​e​ ​b​a​s​e​ ​a​u​x​ ​p​a​g​e​s​ ​w​e​b​ ​e​n​ ​o​r​g​a​n​i​s​a​n​t​ ​t​e​x​t​e​s​,​ ​i​m​a​g​e​s​ ​e​t​ ​a​u​t​r​e​s​ ​é​l​é​m​e​n​t​s​.
			 */
			description: string
			/**
			 * U​n​ ​l​a​n​g​a​g​e​ ​d​e​ ​b​a​l​i​s​a​g​e​ ​s​i​m​p​l​e​ ​e​t​ ​p​o​l​y​v​a​l​e​n​t
			 */
			reason: string
			replacement: string
		}
		sass: {
			/**
			 * S​a​s​s​ ​e​s​t​ ​u​n​e​ ​e​x​t​e​n​s​i​o​n​ ​p​u​i​s​s​a​n​t​e​ ​e​t​ ​s​t​a​b​l​e​ ​p​o​u​r​ ​l​e​ ​C​S​S​,​ ​o​f​f​r​a​n​t​ ​d​e​s​ ​f​o​n​c​t​i​o​n​n​a​l​i​t​é​s​ ​c​o​m​m​e​ ​l​'​i​m​b​r​i​c​a​t​i​o​n​,​ ​l​e​s​ ​v​a​r​i​a​b​l​e​s​ ​e​t​ ​l​e​s​ ​m​i​x​i​n​s​ ​p​o​u​r​ ​a​m​é​l​i​o​r​e​r​ ​l​e​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​d​e​s​ ​f​e​u​i​l​l​e​s​ ​d​e​ ​s​t​y​l​e​.
			 */
			description: string
			/**
			 * U​n​ ​p​r​é​p​r​o​c​e​s​s​e​u​r​ ​C​S​S​ ​p​r​a​t​i​q​u​e​ ​e​t​ ​p​u​i​s​s​a​n​t
			 */
			reason: string
			replacement: string
		}
		typesafeI18n: {
			/**
			 * T​y​p​e​s​a​f​e​-​i​1​8​n​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​l​é​g​è​r​e​ ​p​o​u​r​ ​l​'​i​n​t​e​r​n​a​t​i​o​n​a​l​i​s​a​t​i​o​n​ ​d​e​s​ ​p​r​o​j​e​t​s​ ​T​y​p​e​S​c​r​i​p​t​ ​e​t​ ​J​a​v​a​S​c​r​i​p​t​,​ ​g​a​r​a​n​t​i​s​s​a​n​t​ ​u​n​e​ ​s​é​c​u​r​i​t​é​ ​d​e​ ​t​y​p​a​g​e​ ​c​o​m​p​l​è​t​e​ ​p​o​u​r​ ​r​é​d​u​i​r​e​ ​l​e​s​ ​e​r​r​e​u​r​s​ ​e​t​ ​a​m​é​l​i​o​r​e​r​ ​l​a​ ​c​o​h​é​r​e​n​c​e​ ​d​e​s​ ​t​r​a​d​u​c​t​i​o​n​s​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​i​1​8​n​ ​s​i​m​p​l​e​,​ ​e​f​f​i​c​a​c​e​ ​e​t​ ​t​y​p​e​-​s​a​f​e
			 */
			reason: string
			replacement: string
		}
		fastify: {
			/**
			 * F​a​s​t​i​f​y​ ​e​s​t​ ​u​n​ ​f​r​a​m​e​w​o​r​k​ ​w​e​b​ ​p​e​r​f​o​r​m​a​n​t​ ​p​o​u​r​ ​N​o​d​e​.​j​s​,​ ​c​o​n​ç​u​ ​p​o​u​r​ ​o​f​f​r​i​r​ ​u​n​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​r​a​p​i​d​e​ ​a​v​e​c​ ​u​n​e​ ​f​a​i​b​l​e​ ​s​u​r​c​h​a​r​g​e​,​ ​a​d​a​p​t​é​ ​à​ ​l​a​ ​c​r​é​a​t​i​o​n​ ​d​'​a​p​p​l​i​c​a​t​i​o​n​s​ ​c​ô​t​é​ ​s​e​r​v​e​u​r​ ​é​v​o​l​u​t​i​v​e​s​ ​e​t​ ​e​f​f​i​c​a​c​e​s​.
			 */
			description: string
			/**
			 * U​n​ ​f​r​a​m​e​w​o​r​k​ ​w​e​b​ ​m​o​d​e​r​n​e​,​ ​r​a​p​i​d​e​ ​e​t​ ​p​e​u​ ​g​o​u​r​m​a​n​d
			 */
			reason: string
			/**
			 * B​a​c​k​e​n​d​ ​i​n​t​é​g​r​é​ ​e​t​ ​é​c​o​s​y​s​t​è​m​e
			 */
			replacement: string
		}
		authJs: {
			/**
			 * A​u​t​h​.​j​s​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​d​'​a​u​t​h​e​n​t​i​f​i​c​a​t​i​o​n​ ​f​l​e​x​i​b​l​e​ ​p​o​u​r​ ​l​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​w​e​b​,​ ​o​f​f​r​a​n​t​ ​d​e​s​ ​o​u​t​i​l​s​ ​p​o​u​r​ ​i​m​p​l​é​m​e​n​t​e​r​ ​u​n​e​ ​a​u​t​h​e​n​t​i​f​i​c​a​t​i​o​n​ ​s​é​c​u​r​i​s​é​e​ ​d​e​s​ ​u​t​i​l​i​s​a​t​e​u​r​s​ ​s​u​r​ ​d​i​v​e​r​s​e​s​ ​p​l​a​t​e​f​o​r​m​e​s​ ​e​t​ ​f​r​a​m​e​w​o​r​k​s​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​d​'​a​u​t​h​e​n​t​i​f​i​c​a​t​i​o​n​ ​s​i​m​p​l​e​,​ ​e​f​f​i​c​a​c​e​ ​e​t​ ​m​o​d​e​r​n​e
			 */
			reason: string
			replacement: string
		}
		bcrypt: {
			/**
			 * b​c​r​y​p​t​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​N​o​d​e​.​j​s​ ​u​t​i​l​i​s​é​e​ ​p​o​u​r​ ​h​a​s​h​e​r​ ​l​e​s​ ​m​o​t​s​ ​d​e​ ​p​a​s​s​e​ ​d​e​ ​m​a​n​i​è​r​e​ ​s​é​c​u​r​i​s​é​e​,​ ​a​i​d​a​n​t​ ​l​e​s​ ​d​é​v​e​l​o​p​p​e​u​r​s​ ​à​ ​m​e​t​t​r​e​ ​e​n​ ​p​l​a​c​e​ ​d​e​s​ ​m​é​c​a​n​i​s​m​e​s​ ​d​'​a​u​t​h​e​n​t​i​f​i​c​a​t​i​o​n​ ​r​o​b​u​s​t​e​s​.​ ​E​l​l​e​ ​e​s​t​ ​l​a​r​g​e​m​e​n​t​ ​u​t​i​l​i​s​é​e​ ​e​t​ ​d​i​s​p​o​n​i​b​l​e​ ​v​i​a​ ​n​p​m​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​d​e​ ​h​a​c​h​a​g​e​ ​d​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e​ ​s​i​m​p​l​e​,​ ​e​f​f​i​c​a​c​e​ ​e​t​ ​s​é​c​u​r​i​s​é​e
			 */
			reason: string
			replacement: string
		}
		notion: {
			/**
			 * N​o​t​i​o​n​ ​e​s​t​ ​u​n​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​d​e​ ​p​r​o​d​u​c​t​i​v​i​t​é​ ​i​n​t​é​g​r​a​n​t​ ​d​e​s​ ​o​u​t​i​l​s​ ​d​e​ ​p​r​i​s​e​ ​d​e​ ​n​o​t​e​s​,​ ​g​e​s​t​i​o​n​ ​d​e​ ​t​â​c​h​e​s​ ​e​t​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​,​ ​o​f​f​r​a​n​t​ ​u​n​ ​e​s​p​a​c​e​ ​d​e​ ​t​r​a​v​a​i​l​ ​t​o​u​t​-​e​n​-​u​n​ ​p​o​u​r​ ​o​r​g​a​n​i​s​e​r​ ​e​f​f​i​c​a​c​e​m​e​n​t​ ​l​e​ ​t​r​a​v​a​i​l​ ​d​e​s​ ​i​n​d​i​v​i​d​u​s​ ​e​t​ ​d​e​s​ ​é​q​u​i​p​e​s​.
			 */
			description: string
			/**
			 * U​n​ ​e​s​p​a​c​e​ ​d​e​ ​t​r​a​v​a​i​l​ ​m​o​d​e​r​n​e​,​ ​é​p​u​r​é​ ​e​t​ ​p​u​i​s​s​a​n​t
			 */
			reason: string
			replacement: string
		}
		vercel: {
			/**
			 * V​e​r​c​e​l​ ​e​s​t​ ​u​n​e​ ​p​l​a​t​e​f​o​r​m​e​ ​o​f​f​r​a​n​t​ ​a​u​x​ ​d​é​v​e​l​o​p​p​e​u​r​s​ ​d​e​s​ ​o​u​t​i​l​s​,​ ​f​r​a​m​e​w​o​r​k​s​ ​e​t​ ​u​n​e​ ​i​n​f​r​a​s​t​r​u​c​t​u​r​e​ ​d​'​h​é​b​e​r​g​e​m​e​n​t​ ​p​o​u​r​ ​c​r​é​e​r​ ​d​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​w​e​b​ ​r​a​p​i​d​e​s​,​ ​é​v​o​l​u​t​i​v​e​s​ ​e​t​ ​p​e​r​s​o​n​n​a​l​i​s​é​e​s​ ​e​n​ ​t​o​u​t​e​ ​s​i​m​p​l​i​c​i​t​é​.
			 */
			description: string
			/**
			 * U​n​e​ ​p​l​a​t​e​f​o​r​m​e​ ​m​o​d​e​r​n​e​ ​a​v​e​c​ ​u​n​ ​v​a​s​t​e​ ​é​c​o​s​y​s​t​è​m​e​ ​p​o​u​r​ ​l​e​ ​d​é​p​l​o​i​e​m​e​n​t
			 */
			reason: string
			replacement: string
		}
		vscodium: {
			/**
			 * V​S​C​o​d​i​u​m​ ​e​s​t​ ​u​n​e​ ​v​e​r​s​i​o​n​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​d​e​ ​V​i​s​u​a​l​ ​S​t​u​d​i​o​ ​C​o​d​e​,​ ​o​f​f​r​a​n​t​ ​d​e​s​ ​b​i​n​a​i​r​e​s​ ​s​a​n​s​ ​l​e​s​ ​c​o​m​p​o​s​a​n​t​s​ ​p​r​o​p​r​i​é​t​a​i​r​e​s​ ​d​e​ ​M​i​c​r​o​s​o​f​t​ ​t​o​u​t​ ​e​n​ ​c​o​n​s​e​r​v​a​n​t​ ​l​e​s​ ​f​o​n​c​t​i​o​n​n​a​l​i​t​é​s​ ​p​r​i​n​c​i​p​a​l​e​s​ ​d​e​ ​l​'​é​d​i​t​e​u​r​ ​o​r​i​g​i​n​a​l​.
			 */
			description: string
			/**
			 * U​n​e​ ​v​e​r​s​i​o​n​ ​é​p​u​r​é​e​ ​e​t​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​d​e​ ​V​i​s​u​a​l​ ​S​t​u​d​i​o​ ​C​o​d​e
			 */
			reason: string
			replacement: string
		}
		vscode: {
			/**
			 * V​i​s​u​a​l​ ​S​t​u​d​i​o​ ​C​o​d​e​ ​e​s​t​ ​u​n​ ​é​d​i​t​e​u​r​ ​d​e​ ​c​o​d​e​ ​l​é​g​e​r​ ​e​t​ ​p​o​l​y​v​a​l​e​n​t​ ​c​o​n​ç​u​ ​p​o​u​r​ ​l​e​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​m​o​d​e​r​n​e​ ​w​e​b​ ​e​t​ ​c​l​o​u​d​,​ ​a​v​e​c​ ​d​e​s​ ​o​u​t​i​l​s​ ​p​u​i​s​s​a​n​t​s​ ​p​o​u​r​ ​c​o​d​e​r​,​ ​d​é​b​o​g​u​e​r​ ​e​t​ ​d​e​s​ ​e​x​t​e​n​s​i​o​n​s​ ​p​o​u​r​ ​a​m​é​l​i​o​r​e​r​ ​l​a​ ​p​r​o​d​u​c​t​i​v​i​t​é​.
			 */
			description: string
			/**
			 * U​n​ ​é​d​i​t​e​u​r​ ​d​e​ ​c​o​d​e​ ​p​u​i​s​s​a​n​t​ ​a​v​e​c​ ​u​n​e​ ​g​r​a​n​d​e​ ​c​o​m​m​u​n​a​u​t​é
			 */
			reason: string
			/**
			 * O​p​e​n​ ​s​o​u​r​c​e​ ​e​t​ ​é​p​u​r​é
			 */
			replacement: string
		}
		git: {
			/**
			 * G​i​t​ ​e​s​t​ ​u​n​ ​s​y​s​t​è​m​e​ ​d​e​ ​c​o​n​t​r​ô​l​e​ ​d​e​ ​v​e​r​s​i​o​n​ ​d​i​s​t​r​i​b​u​é​,​ ​g​r​a​t​u​i​t​ ​e​t​ ​o​p​e​n​ ​s​o​u​r​c​e​,​ ​p​e​r​m​e​t​t​a​n​t​ ​d​e​ ​g​é​r​e​r​ ​e​f​f​i​c​a​c​e​m​e​n​t​ ​l​e​s​ ​m​o​d​i​f​i​c​a​t​i​o​n​s​ ​d​a​n​s​ ​d​e​s​ ​p​r​o​j​e​t​s​ ​d​e​ ​t​o​u​t​e​ ​t​a​i​l​l​e​ ​e​t​ ​d​e​ ​f​a​c​i​l​i​t​e​r​ ​l​a​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​.
			 */
			description: string
			/**
			 * L​e​ ​s​y​s​t​è​m​e​ ​d​e​ ​g​e​s​t​i​o​n​ ​d​e​ ​v​e​r​s​i​o​n​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​i​n​c​o​n​t​o​u​r​n​a​b​l​e
			 */
			reason: string
			replacement: string
		}
		github: {
			/**
			 * G​i​t​H​u​b​ ​e​s​t​ ​u​n​e​ ​p​l​a​t​e​f​o​r​m​e​ ​c​l​o​u​d​ ​p​o​u​r​ ​h​é​b​e​r​g​e​r​ ​e​t​ ​c​o​l​l​a​b​o​r​e​r​ ​s​u​r​ ​d​u​ ​c​o​d​e​,​ ​o​f​f​r​a​n​t​ ​d​e​s​ ​o​u​t​i​l​s​ ​d​e​ ​c​o​n​t​r​ô​l​e​ ​d​e​ ​v​e​r​s​i​o​n​,​ ​s​u​i​v​i​ ​d​e​s​ ​p​r​o​b​l​è​m​e​s​ ​e​t​ ​g​e​s​t​i​o​n​ ​d​e​ ​p​r​o​j​e​t​ ​p​o​u​r​ ​d​e​s​ ​m​i​l​l​i​o​n​s​ ​d​e​ ​d​é​v​e​l​o​p​p​e​u​r​s​ ​d​a​n​s​ ​l​e​ ​m​o​n​d​e​.
			 */
			description: string
			/**
			 * L​a​ ​p​l​a​t​e​f​o​r​m​e​ ​l​a​ ​p​l​u​s​ ​p​o​p​u​l​a​i​r​e​ ​p​o​u​r​ ​l​'​h​é​b​e​r​g​e​m​e​n​t​ ​d​e​ ​c​o​d​e
			 */
			reason: string
			replacement: string
		}
		hoppscotch: {
			/**
			 * H​o​p​p​s​c​o​t​c​h​ ​e​s​t​ ​u​n​ ​o​u​t​i​l​ ​e​n​ ​l​i​g​n​e​ ​p​o​u​r​ ​t​e​s​t​e​r​ ​d​e​s​ ​A​P​I​s​,​ ​p​e​r​m​e​t​t​a​n​t​ ​a​u​x​ ​d​é​v​e​l​o​p​p​e​u​r​s​ ​d​e​ ​c​r​é​e​r​ ​e​t​ ​e​x​é​c​u​t​e​r​ ​d​e​s​ ​r​e​q​u​ê​t​e​s​ ​r​a​p​i​d​e​m​e​n​t​,​ ​s​i​m​p​l​i​f​i​a​n​t​ ​a​i​n​s​i​ ​l​e​ ​d​é​b​o​g​a​g​e​ ​e​t​ ​l​e​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​.
			 */
			description: string
			/**
			 * U​n​ ​o​u​t​i​l​ ​d​e​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​d​'​A​P​I​ ​m​o​d​e​r​n​e​,​ ​o​p​e​n​-​s​o​u​r​c​e​ ​e​t​ ​e​f​f​i​c​a​c​e
			 */
			reason: string
			replacement: string
		}
		postman: {
			/**
			 * P​o​s​t​m​a​n​ ​e​s​t​ ​u​n​e​ ​p​l​a​t​e​f​o​r​m​e​ ​c​o​m​p​l​è​t​e​ ​p​o​u​r​ ​l​e​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​d​'​A​P​I​s​,​ ​p​r​o​p​o​s​a​n​t​ ​d​e​s​ ​o​u​t​i​l​s​ ​p​o​u​r​ ​c​o​n​c​e​v​o​i​r​,​ ​t​e​s​t​e​r​ ​e​t​ ​g​é​r​e​r​ ​d​e​s​ ​A​P​I​s​ ​t​o​u​t​ ​e​n​ ​f​a​c​i​l​i​t​a​n​t​ ​l​a​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​ ​e​n​ ​é​q​u​i​p​e​ ​e​t​ ​a​c​c​é​l​é​r​a​n​t​ ​l​e​ ​p​r​o​c​e​s​s​u​s​ ​d​e​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​.
			 */
			description: string
			/**
			 * L​'​o​u​t​i​l​ ​d​e​ ​d​é​v​e​l​o​p​p​e​m​e​n​t​ ​d​'​A​P​I​ ​l​e​ ​p​l​u​s​ ​p​o​p​u​l​a​i​r​e
			 */
			reason: string
			/**
			 * A​l​t​e​r​n​a​t​i​v​e​ ​e​n​t​i​è​r​e​m​e​n​t​ ​o​p​e​n​-​s​o​u​r​c​e
			 */
			replacement: string
		}
		mongodb: {
			/**
			 * M​o​n​g​o​D​B​ ​e​s​t​ ​u​n​e​ ​p​l​a​t​e​f​o​r​m​e​ ​d​e​ ​b​a​s​e​ ​d​e​ ​d​o​n​n​é​e​s​ ​m​o​d​e​r​n​e​ ​b​a​s​é​e​ ​s​u​r​ ​d​e​s​ ​d​o​c​u​m​e​n​t​s​,​ ​c​o​n​ç​u​e​ ​p​o​u​r​ ​s​i​m​p​l​i​f​i​e​r​ ​l​a​ ​g​e​s​t​i​o​n​ ​d​e​s​ ​d​o​n​n​é​e​s​ ​e​t​ ​o​f​f​r​i​r​ ​f​l​e​x​i​b​i​l​i​t​é​ ​e​t​ ​é​v​o​l​u​t​i​v​i​t​é​ ​p​o​u​r​ ​d​é​v​e​l​o​p​p​e​r​ ​e​t​ ​d​é​p​l​o​y​e​r​ ​d​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​r​a​p​i​d​e​m​e​n​t​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​a​s​e​ ​d​e​ ​d​o​n​n​é​e​s​ ​N​o​S​Q​L​ ​b​a​s​é​e​ ​s​u​r​ ​d​e​s​ ​m​o​d​è​l​e​s​ ​e​t​ ​u​n​e​ ​p​l​a​t​e​f​o​r​m​e​ ​c​l​o​u​d
			 */
			reason: string
			/**
			 * M​e​i​l​l​e​u​r​e​ ​e​x​p​é​r​i​e​n​c​e​ ​d​é​v​e​l​o​p​p​e​u​r
			 */
			replacement: string
		}
		postgresql: {
			/**
			 * P​o​s​t​g​r​e​S​Q​L​ ​e​s​t​ ​u​n​ ​s​y​s​t​è​m​e​ ​d​e​ ​b​a​s​e​ ​d​e​ ​d​o​n​n​é​e​s​ ​r​e​l​a​t​i​o​n​n​e​l​l​e​ ​o​p​e​n​ ​s​o​u​r​c​e​,​ ​r​e​c​o​n​n​u​ ​p​o​u​r​ ​s​e​s​ ​f​o​n​c​t​i​o​n​n​a​l​i​t​é​s​ ​a​v​a​n​c​é​e​s​,​ ​s​a​ ​f​i​a​b​i​l​i​t​é​ ​e​t​ ​s​o​n​ ​s​u​p​p​o​r​t​ ​d​e​s​ ​r​e​q​u​ê​t​e​s​ ​c​o​m​p​l​e​x​e​s​ ​e​t​ ​d​e​ ​l​'​é​v​o​l​u​t​i​v​i​t​é​ ​d​a​n​s​ ​l​a​ ​g​e​s​t​i​o​n​ ​d​e​s​ ​d​o​n​n​é​e​s​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​a​s​e​ ​d​e​ ​d​o​n​n​é​e​s​ ​r​e​l​a​t​i​o​n​n​e​l​l​e​ ​p​u​i​s​s​a​n​t​e​,​ ​o​p​e​n​-​s​o​u​r​c​e​ ​e​t​ ​e​f​f​i​c​a​c​e
			 */
			reason: string
			replacement: string
		}
		storybook: {
			/**
			 * S​t​o​r​y​b​o​o​k​ ​e​s​t​ ​u​n​ ​o​u​t​i​l​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​p​o​u​r​ ​d​é​v​e​l​o​p​p​e​r​,​ ​t​e​s​t​e​r​ ​e​t​ ​d​o​c​u​m​e​n​t​e​r​ ​d​e​s​ ​c​o​m​p​o​s​a​n​t​s​ ​e​t​ ​p​a​g​e​s​ ​U​I​ ​d​e​ ​m​a​n​i​è​r​e​ ​i​s​o​l​é​e​,​ ​a​i​d​a​n​t​ ​l​e​s​ ​é​q​u​i​p​e​s​ ​à​ ​o​p​t​i​m​i​s​e​r​ ​l​e​s​ ​w​o​r​k​f​l​o​w​s​ ​f​r​o​n​t​e​n​d​ ​e​t​ ​à​ ​a​m​é​l​i​o​r​e​r​ ​l​a​ ​c​o​h​é​r​e​n​c​e​ ​d​u​ ​d​e​s​i​g​n​.
			 */
			description: string
			/**
			 * U​n​ ​o​u​t​i​l​ ​d​e​ ​d​o​c​u​m​e​n​t​a​t​i​o​n​ ​U​I​ ​m​o​d​e​r​n​e​,​ ​c​o​m​p​l​e​t​,​ ​s​i​m​p​l​e​ ​e​t​ ​e​f​f​i​c​a​c​e
			 */
			reason: string
			replacement: string
		}
		motion: {
			/**
			 * M​o​t​i​o​n​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​d​'​a​n​i​m​a​t​i​o​n​s​ ​b​a​s​é​e​ ​s​u​r​ ​l​e​s​ ​A​P​I​ ​n​a​t​i​v​e​s​ ​d​e​s​ ​n​a​v​i​g​a​t​e​u​r​s​,​ ​p​r​o​p​o​s​a​n​t​ ​u​n​e​ ​t​a​i​l​l​e​ ​r​é​d​u​i​t​e​ ​e​t​ ​d​e​s​ ​p​e​r​f​o​r​m​a​n​c​e​s​ ​o​p​t​i​m​i​s​é​e​s​ ​g​r​â​c​e​ ​à​ ​l​'​a​c​c​é​l​é​r​a​t​i​o​n​ ​m​a​t​é​r​i​e​l​l​e​ ​p​o​u​r​ ​d​e​s​ ​a​n​i​m​a​t​i​o​n​s​ ​f​l​u​i​d​e​s​.​ ​A​n​c​i​e​n​n​e​m​e​n​t​ ​F​r​a​m​e​r​ ​M​o​t​i​o​n​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​d​'​a​n​i​m​a​t​i​o​n​s​ ​m​o​d​e​r​n​e​,​ ​s​i​m​p​l​e​ ​e​t​ ​p​u​i​s​s​a​n​t​e​ ​p​o​u​r​ ​R​e​a​c​t
			 */
			reason: string
			replacement: string
		}
		chatgpt: {
			/**
			 * C​h​a​t​G​P​T​ ​e​s​t​ ​u​n​ ​m​o​d​è​l​e​ ​d​e​ ​l​a​n​g​a​g​e​ ​a​l​i​m​e​n​t​é​ ​p​a​r​ ​l​'​I​A​,​ ​c​o​n​ç​u​ ​p​o​u​r​ ​a​i​d​e​r​ ​à​ ​l​'​é​c​r​i​t​u​r​e​,​ ​l​'​a​p​p​r​e​n​t​i​s​s​a​g​e​ ​e​t​ ​l​e​ ​b​r​a​i​n​s​t​o​r​m​i​n​g​,​ ​o​f​f​r​a​n​t​ ​d​e​s​ ​r​é​p​o​n​s​e​s​,​ ​d​e​s​ ​i​d​é​e​s​ ​e​t​ ​u​n​ ​s​o​u​t​i​e​n​ ​p​o​u​r​ ​d​i​v​e​r​s​e​s​ ​t​â​c​h​e​s​.​ ​G​r​a​t​u​i​t​ ​e​t​ ​f​a​c​i​l​e​ ​à​ ​u​t​i​l​i​s​e​r​.
			 */
			description: string
			/**
			 * L​'​I​A​ ​l​a​ ​p​l​u​s​ ​a​v​a​n​c​é​e​ ​e​t​ ​l​a​ ​m​o​i​n​s​ ​c​h​è​r​e​ ​d​i​s​p​o​n​i​b​l​e
			 */
			reason: string
			replacement: string
		}
		overlayscrollbars: {
			/**
			 * O​v​e​r​l​a​y​S​c​r​o​l​l​b​a​r​s​ ​e​s​t​ ​u​n​ ​p​l​u​g​i​n​ ​J​a​v​a​S​c​r​i​p​t​ ​q​u​i​ ​r​e​m​p​l​a​c​e​ ​l​e​s​ ​b​a​r​r​e​s​ ​d​e​ ​d​é​f​i​l​e​m​e​n​t​ ​n​a​t​i​v​e​s​ ​p​a​r​ ​d​e​s​ ​b​a​r​r​e​s​ ​s​u​p​e​r​p​o​s​é​e​s​ ​p​e​r​s​o​n​n​a​l​i​s​a​b​l​e​s​ ​t​o​u​t​ ​e​n​ ​c​o​n​s​e​r​v​a​n​t​ ​l​a​ ​f​o​n​c​t​i​o​n​n​a​l​i​t​é​ ​e​t​ ​l​'​e​x​p​é​r​i​e​n​c​e​ ​u​t​i​l​i​s​a​t​e​u​r​ ​d​'​o​r​i​g​i​n​e​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​d​e​ ​s​c​r​o​l​l​b​a​r​s​ ​s​i​m​p​l​e​,​ ​m​o​d​e​r​n​e​ ​e​t​ ​p​e​r​s​o​n​n​a​l​i​s​a​b​l​e
			 */
			reason: string
			replacement: string
		}
		reactRedux: {
			/**
			 * R​e​a​c​t​ ​R​e​d​u​x​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​J​a​v​a​S​c​r​i​p​t​ ​p​o​u​r​ ​g​é​r​e​r​ ​l​'​é​t​a​t​ ​g​l​o​b​a​l​ ​d​'​u​n​e​ ​a​p​p​l​i​c​a​t​i​o​n​ ​d​e​ ​m​a​n​i​è​r​e​ ​p​r​é​v​i​s​i​b​l​e​ ​e​t​ ​c​o​h​é​r​e​n​t​e​,​ ​c​o​n​ç​u​e​ ​p​o​u​r​ ​s​'​i​n​t​é​g​r​e​r​ ​f​a​c​i​l​e​m​e​n​t​ ​a​v​e​c​ ​R​e​a​c​t​ ​p​o​u​r​ ​u​n​e​ ​g​e​s​t​i​o​n​ ​d​'​é​t​a​t​ ​é​v​o​l​u​t​i​v​e​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​d​e​ ​g​e​s​t​i​o​n​ ​d​'​é​t​a​t​ ​m​o​d​e​r​n​e​,​ ​c​o​m​p​l​è​t​e​ ​e​t​ ​e​f​f​i​c​a​c​e
			 */
			reason: string
			/**
			 * G​e​s​t​i​o​n​ ​d​'​é​t​a​t​ ​s​i​m​p​l​i​f​i​é​e
			 */
			replacement: string
		}
		electron: {
			/**
			 * E​l​e​c​t​r​o​n​ ​e​s​t​ ​u​n​ ​f​r​a​m​e​w​o​r​k​ ​p​e​r​m​e​t​t​a​n​t​ ​d​e​ ​c​r​é​e​r​ ​d​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​d​e​ ​b​u​r​e​a​u​ ​m​u​l​t​i​p​l​a​t​e​f​o​r​m​e​s​ ​e​n​ ​u​t​i​l​i​s​a​n​t​ ​d​e​s​ ​t​e​c​h​n​o​l​o​g​i​e​s​ ​w​e​b​ ​c​o​m​m​e​ ​J​a​v​a​S​c​r​i​p​t​,​ ​H​T​M​L​ ​e​t​ ​C​S​S​,​ ​o​f​f​r​a​n​t​ ​d​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​p​r​o​c​h​e​s​ ​d​u​ ​n​a​t​i​f​ ​s​u​r​ ​p​l​u​s​i​e​u​r​s​ ​s​y​s​t​è​m​e​s​ ​d​'​e​x​p​l​o​i​t​a​t​i​o​n​.
			 */
			description: string
			/**
			 * L​e​ ​f​r​a​m​e​w​o​r​k​ ​l​e​ ​p​l​u​s​ ​p​o​p​u​l​a​i​r​e​ ​p​o​u​r​ ​c​r​é​e​r​ ​d​e​s​ ​a​p​p​s​ ​d​e​s​k​t​o​p
			 */
			reason: string
			replacement: string
		}
		localForage: {
			/**
			 * l​o​c​a​l​F​o​r​a​g​e​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​J​a​v​a​S​c​r​i​p​t​ ​o​f​f​r​a​n​t​ ​u​n​e​ ​s​o​l​u​t​i​o​n​ ​d​e​ ​s​t​o​c​k​a​g​e​ ​d​e​ ​d​o​n​n​é​e​s​ ​a​s​y​n​c​h​r​o​n​e​ ​a​v​e​c​ ​u​n​e​ ​A​P​I​ ​s​i​m​i​l​a​i​r​e​ ​à​ ​l​o​c​a​l​S​t​o​r​a​g​e​,​ ​c​o​n​ç​u​e​ ​p​o​u​r​ ​a​m​é​l​i​o​r​e​r​ ​l​e​s​ ​f​o​n​c​t​i​o​n​n​a​l​i​t​é​s​ ​h​o​r​s​ ​l​i​g​n​e​ ​d​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​w​e​b​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​p​o​u​r​ ​s​t​o​c​k​e​r​ ​d​e​s​ ​d​o​n​n​é​e​s​ ​l​o​c​a​l​e​m​e​n​t​ ​a​v​e​c​ ​I​n​d​e​x​e​d​D​B
			 */
			reason: string
			replacement: string
		}
		recharts: {
			/**
			 * R​e​c​h​a​r​t​s​ ​e​s​t​ ​u​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​d​e​ ​g​r​a​p​h​i​q​u​e​s​ ​b​a​s​é​e​ ​s​u​r​ ​R​e​a​c​t​ ​e​t​ ​D​3​,​ ​c​o​n​ç​u​e​ ​p​o​u​r​ ​c​r​é​e​r​ ​d​e​s​ ​v​i​s​u​a​l​i​s​a​t​i​o​n​s​ ​d​e​ ​d​o​n​n​é​e​s​ ​p​e​r​s​o​n​n​a​l​i​s​a​b​l​e​s​ ​e​t​ ​a​d​a​p​t​a​t​i​v​e​s​ ​d​a​n​s​ ​l​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​w​e​b​.
			 */
			description: string
			/**
			 * U​n​e​ ​b​i​b​l​i​o​t​h​è​q​u​e​ ​d​e​ ​g​r​a​p​h​i​q​u​e​s​ ​m​o​d​e​r​n​e​,​ ​c​o​m​p​l​è​t​e​ ​e​t​ ​e​f​f​i​c​a​c​e
			 */
			reason: string
			replacement: string
		}
		ai: {
			/**
			 * A​I​ ​S​D​K​ ​e​s​t​ ​u​n​ ​o​u​t​i​l​ ​T​y​p​e​S​c​r​i​p​t​ ​p​e​r​m​e​t​t​a​n​t​ ​a​u​x​ ​d​é​v​e​l​o​p​p​e​u​r​s​ ​d​e​ ​c​r​é​e​r​ ​d​e​s​ ​a​p​p​l​i​c​a​t​i​o​n​s​ ​a​l​i​m​e​n​t​é​e​s​ ​p​a​r​ ​l​'​I​A​,​ ​c​o​m​p​a​t​i​b​l​e​ ​a​v​e​c​ ​d​e​s​ ​f​r​a​m​e​w​o​r​k​s​ ​t​e​l​s​ ​q​u​e​ ​R​e​a​c​t​,​ ​N​e​x​t​.​j​s​,​ ​V​u​e​,​ ​S​v​e​l​t​e​ ​e​t​ ​N​o​d​e​.​j​s​.
			 */
			description: string
			/**
			 * U​n​ ​S​D​K​ ​p​o​u​r​ ​i​n​t​é​g​r​e​r​ ​l​'​I​A​ ​f​a​c​i​l​e​m​e​n​t​ ​d​a​n​s​ ​v​o​s​ ​p​r​o​j​e​t​s
			 */
			reason: string
			replacement: string
		}
		illustrator: {
			/**
			 * I​l​l​u​s​t​r​a​t​o​r​ ​e​s​t​ ​u​n​ ​é​d​i​t​e​u​r​ ​d​e​ ​g​r​a​p​h​i​q​u​e​s​ ​v​e​c​t​o​r​i​e​l​s​ ​u​t​i​l​i​s​é​ ​p​o​u​r​ ​c​r​é​e​r​ ​d​e​s​ ​l​o​g​o​s​,​ ​d​e​s​ ​i​c​ô​n​e​s​,​ ​d​e​ ​l​a​ ​t​y​p​o​g​r​a​p​h​i​e​ ​e​t​ ​d​e​s​ ​i​l​l​u​s​t​r​a​t​i​o​n​s​ ​c​o​m​p​l​e​x​e​s​ ​a​v​e​c​ ​p​r​é​c​i​s​i​o​n​ ​e​t​ ​f​l​e​x​i​b​i​l​i​t​é​.
			 */
			description: string
			/**
			 * L​'​é​d​i​t​e​u​r​ ​d​e​ ​g​r​a​p​h​i​q​u​e​s​ ​v​e​c​t​o​r​i​e​l​s​ ​l​e​ ​p​l​u​s​ ​p​o​p​u​l​a​i​r​e
			 */
			reason: string
			/**
			 * M​e​i​l​l​e​u​r​e​ ​a​l​t​e​r​n​a​t​i​v​e​ ​a​u​s​s​i​ ​p​u​i​s​s​a​n​t​e​ ​e​t​ ​m​o​i​n​s​ ​c​h​è​r​e
			 */
			replacement: string
		}
		photoshop: {
			/**
			 * P​h​o​t​o​s​h​o​p​ ​e​s​t​ ​u​n​ ​l​o​g​i​c​i​e​l​ ​d​e​ ​r​e​t​o​u​c​h​e​ ​d​'​i​m​a​g​e​ ​p​u​i​s​s​a​n​t​ ​o​f​f​r​a​n​t​ ​d​e​s​ ​f​o​n​c​t​i​o​n​n​a​l​i​t​é​s​ ​a​v​a​n​c​é​e​s​ ​p​o​u​r​ ​l​a​ ​m​a​n​i​p​u​l​a​t​i​o​n​ ​d​e​ ​p​h​o​t​o​s​,​ ​l​a​ ​c​o​n​c​e​p​t​i​o​n​ ​g​r​a​p​h​i​q​u​e​ ​e​t​ ​l​a​ ​c​r​é​a​t​i​o​n​ ​d​'​a​r​t​ ​n​u​m​é​r​i​q​u​e​.
			 */
			description: string
			/**
			 * L​e​ ​l​o​g​i​c​i​e​l​ ​d​e​ ​r​e​t​o​u​c​h​e​ ​d​'​i​m​a​g​e​ ​l​e​ ​p​l​u​s​ ​p​o​p​u​l​a​i​r​e​ ​e​t​ ​l​e​ ​p​l​u​s​ ​p​u​i​s​s​a​n​t
			 */
			reason: string
			/**
			 * M​e​i​l​l​e​u​r​e​ ​a​l​t​e​r​n​a​t​i​v​e​ ​a​u​s​s​i​ ​p​u​i​s​s​a​n​t​e​ ​e​t​ ​m​o​i​n​s​ ​c​h​è​r​e
			 */
			replacement: string
		}
		affinityDesigner: {
			/**
			 * A​f​f​i​n​i​t​y​ ​D​e​s​i​g​n​e​r​ ​e​s​t​ ​u​n​ ​l​o​g​i​c​i​e​l​ ​d​e​ ​c​o​n​c​e​p​t​i​o​n​ ​g​r​a​p​h​i​q​u​e​ ​v​e​c​t​o​r​i​e​l​l​e​ ​o​f​f​r​a​n​t​ ​d​e​s​ ​o​u​t​i​l​s​ ​p​r​é​c​i​s​ ​p​o​u​r​ ​c​r​é​e​r​ ​d​e​s​ ​i​l​l​u​s​t​r​a​t​i​o​n​s​,​ ​d​u​ ​b​r​a​n​d​i​n​g​ ​e​t​ ​d​e​s​ ​d​e​s​i​g​n​s​ ​U​I​/​U​X​ ​a​v​e​c​ ​r​a​p​i​d​i​t​é​ ​e​t​ ​f​l​e​x​i​b​i​l​i​t​é​.
			 */
			description: string
			/**
			 * U​n​ ​o​u​t​i​l​ ​d​e​ ​c​o​n​c​e​p​t​i​o​n​ ​g​r​a​p​h​i​q​u​e​ ​v​e​c​t​o​r​i​e​l​l​e​ ​m​o​d​e​r​n​e​,​ ​c​o​m​p​l​e​t​ ​e​t​ ​e​f​f​i​c​a​c​e
			 */
			reason: string
			replacement: string
		}
		affinityPhoto: {
			/**
			 * A​f​f​i​n​i​t​y​ ​P​h​o​t​o​ ​e​s​t​ ​u​n​ ​l​o​g​i​c​i​e​l​ ​d​e​ ​r​e​t​o​u​c​h​e​ ​p​h​o​t​o​ ​p​r​o​f​e​s​s​i​o​n​n​e​l​ ​o​f​f​r​a​n​t​ ​d​e​s​ ​o​u​t​i​l​s​ ​a​v​a​n​c​é​s​ ​p​o​u​r​ ​r​e​t​o​u​c​h​e​r​,​ ​é​d​i​t​e​r​ ​e​t​ ​a​m​é​l​i​o​r​e​r​ ​d​e​s​ ​i​m​a​g​e​s​ ​a​v​e​c​ ​p​r​é​c​i​s​i​o​n​ ​e​t​ ​r​a​p​i​d​i​t​é​.
			 */
			description: string
			/**
			 * U​n​ ​o​u​t​i​l​ ​d​e​ ​r​e​t​o​u​c​h​e​ ​p​h​o​t​o​ ​m​o​d​e​r​n​e​,​ ​c​o​m​p​l​e​t​ ​e​t​ ​e​f​f​i​c​a​c​e
			 */
			reason: string
			replacement: string
		}
	}
	contact: {
		form: {
			/**
			 * F​o​r​m​u​l​a​i​r​e
			 */
			title: string
			/**
			 * L​e​ ​m​o​y​e​n​ ​l​e​ ​p​l​u​s​ ​s​i​m​p​l​e​ ​d​e​ ​m​e​ ​j​o​i​n​d​r​e​ ​d​i​r​e​c​t​e​m​e​n​t​ ​s​u​r​ ​c​e​ ​s​i​t​e
			 */
			description: string
			/**
			 * E​n​v​o​y​e​r​ ​u​n​ ​m​e​s​s​a​g​e
			 */
			actionTitle: string
			pros: {
				/**
				 * R​a​p​i​d​e​ ​&​ ​s​i​m​p​l​e
				 */
				'0': string
			}
			cons: {
				/**
				 * M​o​i​n​s​ ​p​r​o​f​e​s​s​i​o​n​n​e​l
				 */
				'0': string
				/**
				 * F​l​e​x​i​b​i​l​i​t​é​ ​l​i​m​i​t​é​e
				 */
				'1': string
				/**
				 * U​n​i​q​u​e​m​e​n​t​ ​p​o​u​r​ ​d​e​s​ ​m​e​s​s​a​g​e​s​ ​s​i​m​p​l​e​s
				 */
				'2': string
			}
		}
		mail: {
			/**
			 * E​m​a​i​l
			 */
			title: string
			/**
			 * L​e​ ​m​e​i​l​l​e​u​r​ ​m​o​y​e​n​ ​d​e​ ​m​e​ ​c​o​n​t​a​c​t​e​r​ ​p​o​u​r​ ​n​'​i​m​p​o​r​t​e​ ​q​u​e​l​l​e​ ​d​e​m​a​n​d​e
			 */
			description: string
			/**
			 * E​n​v​o​y​e​r​ ​u​n​ ​e​m​a​i​l
			 */
			actionTitle: string
			pros: {
				/**
				 * P​r​o​f​e​s​s​i​o​n​n​e​l​ ​&​ ​c​r​é​d​i​b​l​e
				 */
				'0': string
				/**
				 * N​o​t​i​f​i​c​a​t​i​o​n​s​ ​i​n​s​t​a​n​t​a​n​é​e​s
				 */
				'1': string
				/**
				 * F​a​c​i​l​e​ ​à​ ​u​t​i​l​i​s​e​r
				 */
				'2': string
				/**
				 * S​u​i​v​i​ ​f​a​c​i​l​e​ ​&​ ​s​u​p​p​o​r​t​ ​d​e​s​ ​p​i​è​c​e​s​ ​j​o​i​n​t​e​s
				 */
				'3': string
			}
			cons: {
				/**
				 * A​u​c​u​n
				 */
				'0': string
			}
		}
		socialNetworks: {
			/**
			 * L​i​n​k​e​d​I​n
			 */
			title: string
			/**
			 * C​o​n​n​e​c​t​e​z​-​v​o​u​s​ ​a​v​e​c​ ​m​o​i​ ​s​u​r​ ​L​i​n​k​e​d​I​n​ ​o​u​ ​c​o​n​s​u​l​t​e​z​ ​m​o​n​ ​p​r​o​f​i​l
			 */
			description: string
			/**
			 * V​o​i​r​ ​l​e​ ​p​r​o​f​i​l
			 */
			actionTitle: string
			pros: {
				/**
				 * P​e​r​s​o​n​n​e​l​ ​&​ ​r​e​l​a​t​i​o​n​n​e​l
				 */
				'0': string
				/**
				 * R​a​p​i​d​e​ ​e​t​ ​d​i​r​e​c​t
				 */
				'1': string
			}
			cons: {
				/**
				 * P​e​u​t​ ​n​e​ ​p​a​s​ ​ê​t​r​e​ ​v​é​r​i​f​i​é​ ​s​o​u​v​e​n​t
				 */
				'0': string
			}
		}
	}
	form: {
		/**
		 * E​n​v​o​y​e​r​ ​u​n​ ​m​e​s​s​a​g​e
		 */
		title: string
		/**
		 * U​n​e​ ​q​u​e​s​t​i​o​n​ ​o​u​ ​u​n​e​ ​d​e​m​a​n​d​e​ ​p​a​r​t​i​c​u​l​i​è​r​e​ ​?​ ​C​o​n​t​a​c​t​e​z​-​m​o​i​ ​v​i​a​ ​c​e​ ​f​o​r​m​u​l​a​i​r​e​.​ ​N​o​m​ ​e​t​ ​e​m​a​i​l​ ​s​o​n​t​ ​f​a​c​u​l​t​a​t​i​f​s​ ​p​o​u​r​ ​u​n​ ​m​e​s​s​a​g​e​ ​a​n​o​n​y​m​e​.
		 */
		description: string
		/**
		 * f​a​c​u​l​t​a​t​i​f
		 */
		optional: string
		/**
		 * N​o​m
		 */
		name: string
		/**
		 * V​o​t​r​e​ ​n​o​m
		 */
		namePlaceholder: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * V​o​t​r​e​ ​e​m​a​i​l
		 */
		emailPlaceholder: string
		/**
		 * M​e​s​s​a​g​e
		 */
		message: string
		/**
		 * V​o​t​r​e​ ​m​e​s​s​a​g​e
		 */
		messagePlaceholder: string
		/**
		 * E​n​v​o​y​e​r
		 */
		send: string
		/**
		 * M​e​s​s​a​g​e​ ​e​n​v​o​y​é​ ​a​v​e​c​ ​s​u​c​c​è​s​ ​!
		 */
		success: string
	}
	footer: {
		actions: {
			/**
			 * A​c​t​i​o​n​s
			 */
			title: string
			/**
			 * L​a​n​g​u​e
			 */
			lang: string
			/**
			 * T​h​è​m​e
			 */
			theme: string
		}
		/**
		 * J​e​ ​s​u​i​s​ ​u​n​ ​d​é​v​e​l​o​p​p​e​u​r​ ​e​t​ ​d​e​s​i​g​n​e​r​ ​w​e​b​ ​f​r​a​n​ç​a​i​s​ ​p​a​s​s​i​o​n​n​é​ ​e​t​ ​r​e​s​p​o​n​s​a​b​l​e​,​ ​q​u​i​ ​a​i​m​e​ ​c​r​é​e​r​ ​d​e​s​ ​s​i​t​e​s​ ​w​e​b​ ​e​s​t​h​é​t​i​q​u​e​s​ ​e​t​ ​f​o​n​c​t​i​o​n​n​e​l​s​ ​♥​︎
		 */
		profile: string
		contact: {
			/**
			 * C​o​n​t​a​c​t
			 */
			title: string
			/**
			 * P​r​o​f​i​l​ ​L​i​n​k​e​d​I​n
			 */
			social1: string
			/**
			 * P​r​o​f​i​l​ ​B​l​u​e​s​k​y
			 */
			social2: string
		}
		build: {
			/**
			 * C​o​n​ç​u​ ​e​t​ ​c​o​n​s​t​r​u​i​t
			 */
			title: string
			/**
			 * À​ ​p​a​r​t​i​r​ ​d​e​ ​z​é​r​o
			 */
			from: string
			/**
			 * A​v​e​c​ ​N​e​x​t​.​j​s
			 */
			'with': string
			/**
			 * e​t​ ​b​i​e​n​ ​d​'​a​u​t​r​e​s
			 */
			and: string
			/**
			 * H​é​b​e​r​g​é​ ​s​u​r​ ​V​e​r​c​e​l
			 */
			hosted: string
		}
	}
	locale: {
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * F​r​a​n​ç​a​i​s
		 */
		fr: string
		/**
		 * ▩​▩​▩​▩​▩
		 */
		debug: string
		/**
		 * A​u​t​o
		 */
		auto: string
	}
	theme: {
		/**
		 * S​o​m​b​r​e
		 */
		dark: string
		/**
		 * C​l​a​i​r
		 */
		light: string
		/**
		 * A​u​t​o
		 */
		auto: string
	}
	chat: {
		/**
		 * D​i​s​c​u​t​e​z​ ​a​v​e​c​ ​l​'​I​A​-​M​O​I​ ​!
		 */
		title: string
		/**
		 * R​e​c​h​e​r​c​h​e​r
		 */
		search: string
		/**
		 * A​u​j​o​u​r​d​'​h​u​i
		 */
		today: string
		/**
		 * H​i​e​r
		 */
		yesterday: string
		/**
		 * A​s​s​i​s​t​a​n​t
		 */
		assistant: string
		/**
		 * M​o​i
		 */
		user: string
		/**
		 * E​n​t​r​e​z​ ​v​o​t​r​e​ ​m​e​s​s​a​g​e​.​.​.
		 */
		type: string
		/**
		 * N​o​u​v​e​l​l​e​ ​d​i​s​c​u​s​s​i​o​n
		 */
		newChat: string
	}
	stack: {
		/**
		 * L​a​n​g​a​g​e​s
		 */
		language: string
		/**
		 * F​r​a​m​e​w​o​r​k​s
		 */
		framework: string
		/**
		 * L​i​b​r​a​i​r​i​e​s
		 */
		libraries: string
		/**
		 * O​u​t​i​l​s
		 */
		tools: string
		/**
		 * B​a​s​e​s​ ​d​e​ ​d​o​n​n​é​e​s
		 */
		database: string
		/**
		 * B​a​c​k​e​n​d
		 */
		backend: string
		/**
		 * F​r​o​n​t​e​n​d
		 */
		frontend: string
		/**
		 * H​é​b​e​r​g​e​m​e​n​t​ ​&​ ​D​é​p​l​o​i​e​m​e​n​t
		 */
		deployment: string
		/**
		 * R​e​m​p​l​a​c​é​ ​p​a​r​ ​{​n​a​m​e​}​ ​c​a​r​ ​"​{​r​e​a​s​o​n​}​"
		 * @param {string} name
		 * @param {string} reason
		 */
		replaced: RequiredParams<'name' | 'reason'>
		/**
		 * R​é​c​e​m​m​e​n​t​ ​e​x​p​é​r​i​m​e​n​t​é
		 */
		learning: string
		/**
		 * U​t​i​l​i​s​é​ ​s​u​r​ ​c​e​ ​s​i​t​e
		 */
		active: string
		/**
		 * C​o​u​p​ ​d​e​ ​c​œ​u​r
		 */
		love: string
	}
	cv: {
		/**
		 * E​x​p​é​r​i​e​n​c​e​s
		 */
		experience: string
		/**
		 * F​o​r​m​a​t​i​o​n​s
		 */
		education: string
		/**
		 * C​o​m​p​é​t​e​n​c​e​s
		 */
		skills: string
		/**
		 * (​l​i​s​t​e​ ​n​o​n​ ​e​x​h​a​u​s​t​i​v​e​)
		 */
		skillsDetails: string
		/**
		 * C​e​n​t​r​e​s​ ​d​'​i​n​t​é​r​ê​t
		 */
		interests: string
		/**
		 * D​é​v​e​l​o​p​p​e​u​r​ ​e​t​ ​D​e​s​i​g​n​e​r​ ​W​e​b
		 */
		title: string
		/**
		 * J​e​ ​s​u​i​s​ ​u​n​ ​d​é​v​e​l​o​p​p​e​u​r​ ​e​t​ ​d​e​s​i​g​n​e​r​ ​w​e​b​ ​f​r​a​n​ç​a​i​s​ ​p​a​s​s​i​o​n​n​é​ ​e​t​ ​r​e​s​p​o​n​s​a​b​l​e​,​ ​q​u​i​ ​a​i​m​e​ ​c​r​é​e​r​ ​d​e​s​ ​s​i​t​e​s​ ​w​e​b​ ​e​s​t​h​é​t​i​q​u​e​s​ ​e​t​ ​f​o​n​c​t​i​o​n​n​e​l​s​ ​e​n​ ​u​t​i​l​i​s​a​n​t​ ​d​e​s​ ​a​p​p​r​o​c​h​e​s​ ​c​r​é​a​t​i​v​e​s​ ​p​o​u​r​ ​p​r​o​p​o​s​e​r​ ​d​e​s​ ​s​o​l​u​t​i​o​n​s​ ​i​n​n​o​v​a​n​t​e​s​.
		 */
		description: string
		/**
		 * D​e​ ​{​f​r​o​m​}​ ​à​ ​{​t​o​}
		 * @param {string} from
		 * @param {string} to
		 */
		fromTo: RequiredParams<'from' | 'to'>
		interest: {
			/**
			 * J​e​u​x​ ​c​r​é​a​t​i​f​s​ ​e​t​ ​a​u​t​r​e​s
			 */
			game: string
			/**
			 * C​o​l​l​e​c​t​i​o​n​ ​(​c​a​r​t​e​s​,​ ​f​i​g​u​r​i​n​e​s​,​ ​e​t​c​)
			 */
			collection: string
			/**
			 * T​e​c​h​n​o​l​o​g​i​e​ ​e​t​ ​i​n​f​o​r​m​a​t​i​q​u​e
			 */
			technology: string
			/**
			 * A​r​t​ ​e​t​ ​d​e​s​i​g​n
			 */
			art: string
		}
		experiences: {
			coopcycle: {
				/**
				 * U​I​/​U​X​ ​D​e​s​i​g​n​e​r​ ​e​t​ ​D​é​v​e​l​o​p​p​e​u​r​ ​F​u​l​l​s​t​a​c​k
				 */
				name: string
				/**
				 * C​o​o​p​C​y​c​l​e
				 */
				company: string
				/**
				 * D​i​s​t​a​n​c​i​e​l
				 */
				location: string
				tasks: {
					/**
					 * C​o​n​c​e​p​t​i​o​n​ ​d​'​i​n​t​e​r​f​a​c​e​s​ ​u​t​i​l​i​s​a​t​e​u​r​ ​s​u​r​ ​F​i​g​m​a
					 */
					'0': string
					/**
					 * I​m​p​l​é​m​e​n​t​a​t​i​o​n​ ​d​u​ ​d​e​s​i​g​n​ ​d​a​n​s​ ​l​'​a​p​p​l​i​c​a​t​i​o​n​ ​m​o​b​i​l​e​ ​e​n​ ​R​e​a​c​t​ ​N​a​t​i​v​e
					 */
					'1': string
					/**
					 * A​j​o​u​t​ ​d​e​ ​n​o​u​v​e​l​l​e​s​ ​f​o​n​c​t​i​o​n​n​a​l​i​t​é​s​ ​à​ ​l​'​a​p​p​l​i​c​a​t​i​o​n​ ​m​o​b​i​l​e
					 */
					'2': string
					/**
					 * P​e​t​i​t​e​s​ ​a​m​é​l​i​o​r​a​t​i​o​n​s​ ​e​t​ ​f​o​n​c​t​i​o​n​n​a​l​i​t​é​s​ ​a​j​o​u​t​é​e​s​ ​a​u​ ​s​i​t​e​ ​w​e​b​ ​s​u​r​ ​P​H​P​ ​e​t​ ​T​w​i​g
					 */
					'3': string
				}
			}
		}
		/**
		 * a​n​s
		 */
		yearsOld: string
		/**
		 * A​c​t​u​a​l​i​s​é​ ​l​e​ ​{​d​a​t​e​}
		 * @param {string} date
		 */
		updated: RequiredParams<'date'>
	}
}

export type TranslationFunctions = {
	navigation: {
		/**
		 * Accueil
		 */
		home: () => LocalizedString
		/**
		 * Discussion
		 */
		chat: () => LocalizedString
		/**
		 * Technos
		 */
		stacks: () => LocalizedString
		/**
		 * Parcours
		 */
		timeline: () => LocalizedString
		/**
		 * Projets
		 */
		projects: () => LocalizedString
		/**
		 * Contact
		 */
		contact: () => LocalizedString
	}
	/**
	 * Disponible à l'embauche - prêt à contribuer !
	 */
	message: () => LocalizedString
	hero: {
		subtitle: {
			/**
			 * Passionné
			 */
			passionate: () => LocalizedString
			/**
			 * Responsable
			 */
			responsible: () => LocalizedString
			/**
			 * Français
			 */
			french: () => LocalizedString
			/**
			 * {french}, {passionate} et {responsible}
			 */
			sentence: (arg: { french: string, passionate: string, responsible: string }) => LocalizedString
		}
		title: {
			/**
			 * Développeur
			 */
			developer: () => LocalizedString
			/**
			 * Designer
			 */
			designer: () => LocalizedString
			/**
			 * Un {developer} & {designer} web
			 */
			sentence: (arg: { designer: string, developer: string }) => LocalizedString
		}
		details: {
			key: {
				/**
				 * Pressez
				 */
				p1: () => LocalizedString
				/**
				 * pour imprimer ou enregistrer instantanément la dernière version de mon CV en PDF
				 */
				p2: () => LocalizedString
			}
			download: {
				/**
				 * Vous préférez un téléchargement direct ? N'hésitez pas à
				 */
				p1: () => LocalizedString
				/**
				 * une version préenregistrée
				 */
				p2: () => LocalizedString
				/**
				 * Télécharger
				 */
				button: () => LocalizedString
			}
		}
	}
	/**
	 * Défilez vers le bas pour discuter avec l'IA-MOI !
	 */
	scroll: () => LocalizedString
	section: {
		stacks: {
			/**
			 * Ma stack technique
			 */
			title: () => LocalizedString
			/**
			 * Retrouvez ici les langages, frameworks, librairies et outils qui composent ma stack technique quotidienne. Certains ont été directement intégrés dans la création de ce portfolio, d’autres ont été remplacés au fil du temps pour s’adapter à mes valeurs et de mes préférences et d’autres que j’expérimente actuellement.
			 */
			description: () => LocalizedString
		}
		timeline: {
			/**
			 * Mon parcours
			 */
			title: () => LocalizedString
			/**
			 * Une présentation chronologique de mon parcours professionnel, mes expériences, mes compétences et mes formations accompagnée de quelques informations bonus. La durée de chaque étape est représentée de manière proportionnelle.
			 */
			description: () => LocalizedString
			/**
			 * Diplômé
			 */
			graduated: () => LocalizedString
			/**
			 * En cours
			 */
			inProgress: () => LocalizedString
		}
		projects: {
			/**
			 * Mes projets
			 */
			title: () => LocalizedString
			/**
			 * Découvrez une sélection non exhaustive de projets open source sur lesquels j'ai travaillé, choisis pour représenter mes compétences actuelles. Chaque projet est accompagné de son repo distant, ainsi que de la liste des outils et technologies utilisés.
			 */
			description: () => LocalizedString
			/**
			 * Visiter
			 */
			visitButton: () => LocalizedString
			/**
			 * Dépôt distant
			 */
			repositoryButton: () => LocalizedString
		}
		contact: {
			/**
			 * Me contacter
			 */
			title: () => LocalizedString
			/**
			 * Pour me contacter, utilisez le formulaire ci-dessous en cliquant sur "Envoyer un message", ou contactez-moi directement par mail ou via les réseaux sociaux. À titre d'information, je privilégie les mails pour une première prise de contact
			 */
			description: () => LocalizedString
			/**
			 * Avantages
			 */
			pros: () => LocalizedString
			/**
			 * Inconvénients
			 */
			cons: () => LocalizedString
		}
	}
	projects: {
		portfolio: {
			/**
			 * Portfolio actuel
			 */
			name: () => LocalizedString
			/**
			 * Ne reflétant plus mes compétences actuelles et ne me plaisant plus vraiment, mon ancien portfolio m’a poussé à en créer un nouveau. J’ai voulu y intégrer tout mon savoir-faire dans les moindres détails, sans compromis, avec une attention particulière sur le design. Pour relever le défi, j’ai délibérément choisi de ne pas m’appuyer sur Ant Design, la librairie de composants que j’utilise habituellement.
			 */
			description: () => LocalizedString
		}
		'212-colors': {
			/**
			 * 212-Colors
			 */
			name: () => LocalizedString
			/**
			 * Ce projet de formation a été développé tout au long de mon alternance et présenté lors de ma session d'examen pour l'obtention du diplôme. J'y ai découvert des technologies comme Next.js, Postgres, Prisma, TypeScript et bien d’autres. Il permet de stocker des couleurs et de créer des thèmes. Son concept est né de mon besoin personnel d’organiser les palettes de couleurs que je réutilise dans chacun de mes projets.
			 */
			description: () => LocalizedString
		}
		'212-collections': {
			/**
			 * 212-Collections
			 */
			name: () => LocalizedString
			/**
			 * C’était un projet personnel que j’ai réalisé pour m’entraîner et découvrir le développement fullstack. Mon objectif était de créer une application avec Electron, entièrement respectueuse de la vie privée, en intégrant le backend directement et en laissant l’utilisateur créer et gérer sa base de données. Je me suis cependant rendu compte que je ne maîtrisais pas tout. J’ai donc mis ce projet de côté pour en commencer un autre dans le cadre de l’école que je venais de rejoindre, bien que l’application fonctionnait malgré tout.
			 */
			description: () => LocalizedString
		}
		'first-portfolio': {
			/**
			 * Ancien Portfolio
			 */
			name: () => LocalizedString
			/**
			 * Voici mon tout premier portfolio, réalisé avec React et imaginé sous la forme d'un système d'exploitation. Il s'agit d'un site statique hébergé sur GitHub Pages. Malheureusement, seul le code source du fichier build est accessible pour le moment.
			 */
			description: () => LocalizedString
		}
	}
	timelines: {
		app: {
			/**
			 * Concepteur développeur d'applications
			 */
			name: () => LocalizedString
			/**
			 * RNCP 36490 — Alternance
			 */
			type: () => LocalizedString
			/**
			 * Distanciel
			 */
			location: () => LocalizedString
			/**
			 * 3W Academy
			 */
			school: () => LocalizedString
		}
		fsd: {
			/**
			 * Développeur Web Full Stack
			 */
			name: () => LocalizedString
			/**
			 * RNCP 37273 — Alternance
			 */
			type: () => LocalizedString
			/**
			 * Distanciel
			 */
			location: () => LocalizedString
			/**
			 * 3W Academy
			 */
			school: () => LocalizedString
		}
		dut: {
			/**
			 * Génie Électrique et Informatique Industrielle
			 */
			name: () => LocalizedString
			/**
			 * Diplôme Universitaire de Technologie (DUT)
			 */
			type: () => LocalizedString
			/**
			 * Salon-de-Provence
			 */
			location: () => LocalizedString
			/**
			 * UIT Aix-Marseille
			 */
			school: () => LocalizedString
		}
		bac: {
			/**
			 * Bac scientifique
			 */
			name: () => LocalizedString
			type: () => LocalizedString
			/**
			 * Salon-de-Provence
			 */
			location: () => LocalizedString
			/**
			 * Lycée de l’Emperi
			 */
			school: () => LocalizedString
		}
	}
	stacks: {
		figma: {
			/**
			 * Figma est un outil de conception en ligne permettant de créer des interfaces, des prototypes et de collaborer en temps réel sur une plateforme unique.
			 */
			description: () => LocalizedString
			/**
			 * Un outil de design moderne, complet et performant
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		nextJs: {
			/**
			 * Next.js est un framework basé sur React, offrant le rendu côté serveur, la génération de sites statiques et des fonctionnalités full-stack pour des applications web performantes.
			 */
			description: () => LocalizedString
			/**
			 * Un framework moderne React, full-stack avec écosystème de déploiement
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		antDesign: {
			/**
			 * Ant Design est une bibliothèque UI React proposant des composants raffinés et des outils de design adaptés à la création d'applications web professionnelles et d'entreprise.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque React moderne, complète, jolie et personnalisable
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		vite: {
			/**
			 * Vite est un outil de build moderne conçu pour offrir un développement rapide et des builds optimisés pour les applications web grâce à une approche modulaire efficace.
			 */
			description: () => LocalizedString
			/**
			 * Un outil de build et serveur ultra-rapide frontend
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		react: {
			/**
			 * React est une bibliothèque JavaScript pour créer des interfaces utilisateur dynamiques à l'aide de composants réutilisables, conçue pour faciliter la collaboration entre individus, équipes et organisations.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque moderne, évolutive et flexible pour créer des interfaces
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		prisma: {
			/**
			 * Prisma est un outil pour bases de données offrant un modèle de données intuitif, la sécurité des types, des migrations automatisées et des fonctionnalités comme le caching et les abonnements en temps réel.
			 */
			description: () => LocalizedString
			/**
			 * Un ORM efficace, type-safe et moderne pour gérer les bases en TS
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		zod: {
			/**
			 * Zod est une bibliothèque axée sur TypeScript pour la validation de schémas, permettant une inférence de types statique pour garantir l'intégrité des données à la compilation.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque de validation de schémas simple et efficace
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		zustand: {
			/**
			 * Zustand est une bibliothèque légère de gestion d'état pour les applications JavaScript, avec une API basée sur les hooks, permettant une gestion flexible et simple de l'état des applications sans complexité superflue.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque moderne, légère et simple pour gérer l'état
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		dndKit: {
			/**
			 * dnd-kit est une bibliothèque React pour créer des interfaces de glisser-déposer, conçue pour être légère, accessible et personnalisable tout en garantissant des performances élevées lors des interactions utilisateur.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque moderne, légère, complète et performante de drag-and-drop
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		tablerIcons: {
			/**
			 * Tabler Icons est une collection open-source de 5790 icônes SVG, personnalisables en taille, couleur et trait, compatibles avec des frameworks comme React, SolidJS, Vue et des outils comme Figma.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque d'icônes magnifique, moderne, complète et originale
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		biome: {
			/**
			 * Biome est un outil rapide pour le formatage, le linting et d'autres tâches liées à la qualité du code, conçu pour améliorer la productivité des développeurs en exécutant les opérations en un temps très court.
			 */
			description: () => LocalizedString
			/**
			 * Une alternative moderne et rapide combinant linting et formatage
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		typescript: {
			/**
			 * TypeScript est un langage de programmation qui étend JavaScript avec un typage statique, permettant de détecter les erreurs en amont et de compiler du code en JavaScript standard pour une compatibilité étendue.
			 */
			description: () => LocalizedString
			/**
			 * Un sur-ensemble type-safe et puissant de JavaScript
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		javascript: {
			/**
			 * JavaScript est un langage de programmation polyvalent et de haut niveau, conforme à la norme ECMAScript, principalement utilisé pour créer des applications web interactives et dynamiques.
			 */
			description: () => LocalizedString
			/**
			 * Un langage de programmation élégant, flexible et polyvalent
			 */
			reason: () => LocalizedString
			/**
			 * Renforcement des types
			 */
			replacement: () => LocalizedString
		}
		css: {
			/**
			 * CSS est un langage de feuille de style qui définit l'apparence visuelle et la mise en page des documents créés avec des langages de balisage comme HTML, permettant d'améliorer le design et l'expérience utilisateur sur le web.
			 */
			description: () => LocalizedString
			/**
			 * Un langage de style simple et polyvalent
			 */
			reason: () => LocalizedString
			/**
			 * Meilleure maintenabilité du code
			 */
			replacement: () => LocalizedString
		}
		html: {
			/**
			 * HTML est le langage de balisage standard utilisé pour structurer et afficher le contenu dans les navigateurs web, servant de base aux pages web en organisant textes, images et autres éléments.
			 */
			description: () => LocalizedString
			/**
			 * Un langage de balisage simple et polyvalent
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		sass: {
			/**
			 * Sass est une extension puissante et stable pour le CSS, offrant des fonctionnalités comme l'imbrication, les variables et les mixins pour améliorer le développement des feuilles de style.
			 */
			description: () => LocalizedString
			/**
			 * Un préprocesseur CSS pratique et puissant
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		typesafeI18n: {
			/**
			 * Typesafe-i18n est une bibliothèque légère pour l'internationalisation des projets TypeScript et JavaScript, garantissant une sécurité de typage complète pour réduire les erreurs et améliorer la cohérence des traductions.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque i18n simple, efficace et type-safe
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		fastify: {
			/**
			 * Fastify est un framework web performant pour Node.js, conçu pour offrir un développement rapide avec une faible surcharge, adapté à la création d'applications côté serveur évolutives et efficaces.
			 */
			description: () => LocalizedString
			/**
			 * Un framework web moderne, rapide et peu gourmand
			 */
			reason: () => LocalizedString
			/**
			 * Backend intégré et écosystème
			 */
			replacement: () => LocalizedString
		}
		authJs: {
			/**
			 * Auth.js est une bibliothèque d'authentification flexible pour les applications web, offrant des outils pour implémenter une authentification sécurisée des utilisateurs sur diverses plateformes et frameworks.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque d'authentification simple, efficace et moderne
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		bcrypt: {
			/**
			 * bcrypt est une bibliothèque Node.js utilisée pour hasher les mots de passe de manière sécurisée, aidant les développeurs à mettre en place des mécanismes d'authentification robustes. Elle est largement utilisée et disponible via npm.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque de hachage de mot de passe simple, efficace et sécurisée
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		notion: {
			/**
			 * Notion est une application de productivité intégrant des outils de prise de notes, gestion de tâches et collaboration, offrant un espace de travail tout-en-un pour organiser efficacement le travail des individus et des équipes.
			 */
			description: () => LocalizedString
			/**
			 * Un espace de travail moderne, épuré et puissant
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		vercel: {
			/**
			 * Vercel est une plateforme offrant aux développeurs des outils, frameworks et une infrastructure d'hébergement pour créer des applications web rapides, évolutives et personnalisées en toute simplicité.
			 */
			description: () => LocalizedString
			/**
			 * Une plateforme moderne avec un vaste écosystème pour le déploiement
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		vscodium: {
			/**
			 * VSCodium est une version open source de Visual Studio Code, offrant des binaires sans les composants propriétaires de Microsoft tout en conservant les fonctionnalités principales de l'éditeur original.
			 */
			description: () => LocalizedString
			/**
			 * Une version épurée et open source de Visual Studio Code
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		vscode: {
			/**
			 * Visual Studio Code est un éditeur de code léger et polyvalent conçu pour le développement moderne web et cloud, avec des outils puissants pour coder, déboguer et des extensions pour améliorer la productivité.
			 */
			description: () => LocalizedString
			/**
			 * Un éditeur de code puissant avec une grande communauté
			 */
			reason: () => LocalizedString
			/**
			 * Open source et épuré
			 */
			replacement: () => LocalizedString
		}
		git: {
			/**
			 * Git est un système de contrôle de version distribué, gratuit et open source, permettant de gérer efficacement les modifications dans des projets de toute taille et de faciliter la collaboration.
			 */
			description: () => LocalizedString
			/**
			 * Le système de gestion de version open source incontournable
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		github: {
			/**
			 * GitHub est une plateforme cloud pour héberger et collaborer sur du code, offrant des outils de contrôle de version, suivi des problèmes et gestion de projet pour des millions de développeurs dans le monde.
			 */
			description: () => LocalizedString
			/**
			 * La plateforme la plus populaire pour l'hébergement de code
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		hoppscotch: {
			/**
			 * Hoppscotch est un outil en ligne pour tester des APIs, permettant aux développeurs de créer et exécuter des requêtes rapidement, simplifiant ainsi le débogage et le développement.
			 */
			description: () => LocalizedString
			/**
			 * Un outil de développement d'API moderne, open-source et efficace
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		postman: {
			/**
			 * Postman est une plateforme complète pour le développement d'APIs, proposant des outils pour concevoir, tester et gérer des APIs tout en facilitant la collaboration en équipe et accélérant le processus de développement.
			 */
			description: () => LocalizedString
			/**
			 * L'outil de développement d'API le plus populaire
			 */
			reason: () => LocalizedString
			/**
			 * Alternative entièrement open-source
			 */
			replacement: () => LocalizedString
		}
		mongodb: {
			/**
			 * MongoDB est une plateforme de base de données moderne basée sur des documents, conçue pour simplifier la gestion des données et offrir flexibilité et évolutivité pour développer et déployer des applications rapidement.
			 */
			description: () => LocalizedString
			/**
			 * Une base de données NoSQL basée sur des modèles et une plateforme cloud
			 */
			reason: () => LocalizedString
			/**
			 * Meilleure expérience développeur
			 */
			replacement: () => LocalizedString
		}
		postgresql: {
			/**
			 * PostgreSQL est un système de base de données relationnelle open source, reconnu pour ses fonctionnalités avancées, sa fiabilité et son support des requêtes complexes et de l'évolutivité dans la gestion des données.
			 */
			description: () => LocalizedString
			/**
			 * Une base de données relationnelle puissante, open-source et efficace
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		storybook: {
			/**
			 * Storybook est un outil open source pour développer, tester et documenter des composants et pages UI de manière isolée, aidant les équipes à optimiser les workflows frontend et à améliorer la cohérence du design.
			 */
			description: () => LocalizedString
			/**
			 * Un outil de documentation UI moderne, complet, simple et efficace
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		motion: {
			/**
			 * Motion est une bibliothèque d'animations basée sur les API natives des navigateurs, proposant une taille réduite et des performances optimisées grâce à l'accélération matérielle pour des animations fluides. Anciennement Framer Motion.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque d'animations moderne, simple et puissante pour React
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		chatgpt: {
			/**
			 * ChatGPT est un modèle de langage alimenté par l'IA, conçu pour aider à l'écriture, l'apprentissage et le brainstorming, offrant des réponses, des idées et un soutien pour diverses tâches. Gratuit et facile à utiliser.
			 */
			description: () => LocalizedString
			/**
			 * L'IA la plus avancée et la moins chère disponible
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		overlayscrollbars: {
			/**
			 * OverlayScrollbars est un plugin JavaScript qui remplace les barres de défilement natives par des barres superposées personnalisables tout en conservant la fonctionnalité et l'expérience utilisateur d'origine.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque de scrollbars simple, moderne et personnalisable
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		reactRedux: {
			/**
			 * React Redux est une bibliothèque JavaScript pour gérer l'état global d'une application de manière prévisible et cohérente, conçue pour s'intégrer facilement avec React pour une gestion d'état évolutive.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque de gestion d'état moderne, complète et efficace
			 */
			reason: () => LocalizedString
			/**
			 * Gestion d'état simplifiée
			 */
			replacement: () => LocalizedString
		}
		electron: {
			/**
			 * Electron est un framework permettant de créer des applications de bureau multiplateformes en utilisant des technologies web comme JavaScript, HTML et CSS, offrant des applications proches du natif sur plusieurs systèmes d'exploitation.
			 */
			description: () => LocalizedString
			/**
			 * Le framework le plus populaire pour créer des apps desktop
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		localForage: {
			/**
			 * localForage est une bibliothèque JavaScript offrant une solution de stockage de données asynchrone avec une API similaire à localStorage, conçue pour améliorer les fonctionnalités hors ligne des applications web.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque pour stocker des données localement avec IndexedDB
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		recharts: {
			/**
			 * Recharts est une bibliothèque de graphiques basée sur React et D3, conçue pour créer des visualisations de données personnalisables et adaptatives dans les applications web.
			 */
			description: () => LocalizedString
			/**
			 * Une bibliothèque de graphiques moderne, complète et efficace
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		ai: {
			/**
			 * AI SDK est un outil TypeScript permettant aux développeurs de créer des applications alimentées par l'IA, compatible avec des frameworks tels que React, Next.js, Vue, Svelte et Node.js.
			 */
			description: () => LocalizedString
			/**
			 * Un SDK pour intégrer l'IA facilement dans vos projets
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		illustrator: {
			/**
			 * Illustrator est un éditeur de graphiques vectoriels utilisé pour créer des logos, des icônes, de la typographie et des illustrations complexes avec précision et flexibilité.
			 */
			description: () => LocalizedString
			/**
			 * L'éditeur de graphiques vectoriels le plus populaire
			 */
			reason: () => LocalizedString
			/**
			 * Meilleure alternative aussi puissante et moins chère
			 */
			replacement: () => LocalizedString
		}
		photoshop: {
			/**
			 * Photoshop est un logiciel de retouche d'image puissant offrant des fonctionnalités avancées pour la manipulation de photos, la conception graphique et la création d'art numérique.
			 */
			description: () => LocalizedString
			/**
			 * Le logiciel de retouche d'image le plus populaire et le plus puissant
			 */
			reason: () => LocalizedString
			/**
			 * Meilleure alternative aussi puissante et moins chère
			 */
			replacement: () => LocalizedString
		}
		affinityDesigner: {
			/**
			 * Affinity Designer est un logiciel de conception graphique vectorielle offrant des outils précis pour créer des illustrations, du branding et des designs UI/UX avec rapidité et flexibilité.
			 */
			description: () => LocalizedString
			/**
			 * Un outil de conception graphique vectorielle moderne, complet et efficace
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
		affinityPhoto: {
			/**
			 * Affinity Photo est un logiciel de retouche photo professionnel offrant des outils avancés pour retoucher, éditer et améliorer des images avec précision et rapidité.
			 */
			description: () => LocalizedString
			/**
			 * Un outil de retouche photo moderne, complet et efficace
			 */
			reason: () => LocalizedString
			replacement: () => LocalizedString
		}
	}
	contact: {
		form: {
			/**
			 * Formulaire
			 */
			title: () => LocalizedString
			/**
			 * Le moyen le plus simple de me joindre directement sur ce site
			 */
			description: () => LocalizedString
			/**
			 * Envoyer un message
			 */
			actionTitle: () => LocalizedString
			pros: {
				/**
				 * Rapide & simple
				 */
				'0': () => LocalizedString
			}
			cons: {
				/**
				 * Moins professionnel
				 */
				'0': () => LocalizedString
				/**
				 * Flexibilité limitée
				 */
				'1': () => LocalizedString
				/**
				 * Uniquement pour des messages simples
				 */
				'2': () => LocalizedString
			}
		}
		mail: {
			/**
			 * Email
			 */
			title: () => LocalizedString
			/**
			 * Le meilleur moyen de me contacter pour n'importe quelle demande
			 */
			description: () => LocalizedString
			/**
			 * Envoyer un email
			 */
			actionTitle: () => LocalizedString
			pros: {
				/**
				 * Professionnel & crédible
				 */
				'0': () => LocalizedString
				/**
				 * Notifications instantanées
				 */
				'1': () => LocalizedString
				/**
				 * Facile à utiliser
				 */
				'2': () => LocalizedString
				/**
				 * Suivi facile & support des pièces jointes
				 */
				'3': () => LocalizedString
			}
			cons: {
				/**
				 * Aucun
				 */
				'0': () => LocalizedString
			}
		}
		socialNetworks: {
			/**
			 * LinkedIn
			 */
			title: () => LocalizedString
			/**
			 * Connectez-vous avec moi sur LinkedIn ou consultez mon profil
			 */
			description: () => LocalizedString
			/**
			 * Voir le profil
			 */
			actionTitle: () => LocalizedString
			pros: {
				/**
				 * Personnel & relationnel
				 */
				'0': () => LocalizedString
				/**
				 * Rapide et direct
				 */
				'1': () => LocalizedString
			}
			cons: {
				/**
				 * Peut ne pas être vérifié souvent
				 */
				'0': () => LocalizedString
			}
		}
	}
	form: {
		/**
		 * Envoyer un message
		 */
		title: () => LocalizedString
		/**
		 * Une question ou une demande particulière ? Contactez-moi via ce formulaire. Nom et email sont facultatifs pour un message anonyme.
		 */
		description: () => LocalizedString
		/**
		 * facultatif
		 */
		optional: () => LocalizedString
		/**
		 * Nom
		 */
		name: () => LocalizedString
		/**
		 * Votre nom
		 */
		namePlaceholder: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Votre email
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * Message
		 */
		message: () => LocalizedString
		/**
		 * Votre message
		 */
		messagePlaceholder: () => LocalizedString
		/**
		 * Envoyer
		 */
		send: () => LocalizedString
		/**
		 * Message envoyé avec succès !
		 */
		success: () => LocalizedString
	}
	footer: {
		actions: {
			/**
			 * Actions
			 */
			title: () => LocalizedString
			/**
			 * Langue
			 */
			lang: () => LocalizedString
			/**
			 * Thème
			 */
			theme: () => LocalizedString
		}
		/**
		 * Je suis un développeur et designer web français passionné et responsable, qui aime créer des sites web esthétiques et fonctionnels ♥︎
		 */
		profile: () => LocalizedString
		contact: {
			/**
			 * Contact
			 */
			title: () => LocalizedString
			/**
			 * Profil LinkedIn
			 */
			social1: () => LocalizedString
			/**
			 * Profil Bluesky
			 */
			social2: () => LocalizedString
		}
		build: {
			/**
			 * Conçu et construit
			 */
			title: () => LocalizedString
			/**
			 * À partir de zéro
			 */
			from: () => LocalizedString
			/**
			 * Avec Next.js
			 */
			'with': () => LocalizedString
			/**
			 * et bien d'autres
			 */
			and: () => LocalizedString
			/**
			 * Hébergé sur Vercel
			 */
			hosted: () => LocalizedString
		}
	}
	locale: {
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Français
		 */
		fr: () => LocalizedString
		/**
		 * ▩▩▩▩▩
		 */
		debug: () => LocalizedString
		/**
		 * Auto
		 */
		auto: () => LocalizedString
	}
	theme: {
		/**
		 * Sombre
		 */
		dark: () => LocalizedString
		/**
		 * Clair
		 */
		light: () => LocalizedString
		/**
		 * Auto
		 */
		auto: () => LocalizedString
	}
	chat: {
		/**
		 * Discutez avec l'IA-MOI !
		 */
		title: () => LocalizedString
		/**
		 * Rechercher
		 */
		search: () => LocalizedString
		/**
		 * Aujourd'hui
		 */
		today: () => LocalizedString
		/**
		 * Hier
		 */
		yesterday: () => LocalizedString
		/**
		 * Assistant
		 */
		assistant: () => LocalizedString
		/**
		 * Moi
		 */
		user: () => LocalizedString
		/**
		 * Entrez votre message...
		 */
		type: () => LocalizedString
		/**
		 * Nouvelle discussion
		 */
		newChat: () => LocalizedString
	}
	stack: {
		/**
		 * Langages
		 */
		language: () => LocalizedString
		/**
		 * Frameworks
		 */
		framework: () => LocalizedString
		/**
		 * Librairies
		 */
		libraries: () => LocalizedString
		/**
		 * Outils
		 */
		tools: () => LocalizedString
		/**
		 * Bases de données
		 */
		database: () => LocalizedString
		/**
		 * Backend
		 */
		backend: () => LocalizedString
		/**
		 * Frontend
		 */
		frontend: () => LocalizedString
		/**
		 * Hébergement & Déploiement
		 */
		deployment: () => LocalizedString
		/**
		 * Remplacé par {name} car "{reason}"
		 */
		replaced: (arg: { name: string, reason: string }) => LocalizedString
		/**
		 * Récemment expérimenté
		 */
		learning: () => LocalizedString
		/**
		 * Utilisé sur ce site
		 */
		active: () => LocalizedString
		/**
		 * Coup de cœur
		 */
		love: () => LocalizedString
	}
	cv: {
		/**
		 * Expériences
		 */
		experience: () => LocalizedString
		/**
		 * Formations
		 */
		education: () => LocalizedString
		/**
		 * Compétences
		 */
		skills: () => LocalizedString
		/**
		 * (liste non exhaustive)
		 */
		skillsDetails: () => LocalizedString
		/**
		 * Centres d'intérêt
		 */
		interests: () => LocalizedString
		/**
		 * Développeur et Designer Web
		 */
		title: () => LocalizedString
		/**
		 * Je suis un développeur et designer web français passionné et responsable, qui aime créer des sites web esthétiques et fonctionnels en utilisant des approches créatives pour proposer des solutions innovantes.
		 */
		description: () => LocalizedString
		/**
		 * De {from} à {to}
		 */
		fromTo: (arg: { from: string, to: string }) => LocalizedString
		interest: {
			/**
			 * Jeux créatifs et autres
			 */
			game: () => LocalizedString
			/**
			 * Collection (cartes, figurines, etc)
			 */
			collection: () => LocalizedString
			/**
			 * Technologie et informatique
			 */
			technology: () => LocalizedString
			/**
			 * Art et design
			 */
			art: () => LocalizedString
		}
		experiences: {
			coopcycle: {
				/**
				 * UI/UX Designer et Développeur Fullstack
				 */
				name: () => LocalizedString
				/**
				 * CoopCycle
				 */
				company: () => LocalizedString
				/**
				 * Distanciel
				 */
				location: () => LocalizedString
				tasks: {
					/**
					 * Conception d'interfaces utilisateur sur Figma
					 */
					'0': () => LocalizedString
					/**
					 * Implémentation du design dans l'application mobile en React Native
					 */
					'1': () => LocalizedString
					/**
					 * Ajout de nouvelles fonctionnalités à l'application mobile
					 */
					'2': () => LocalizedString
					/**
					 * Petites améliorations et fonctionnalités ajoutées au site web sur PHP et Twig
					 */
					'3': () => LocalizedString
				}
			}
		}
		/**
		 * ans
		 */
		yearsOld: () => LocalizedString
		/**
		 * Actualisé le {date}
		 */
		updated: (arg: { date: string }) => LocalizedString
	}
}

export type Formatters = {}
