// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navigation: {
		/**
		 * A​c​c​u​e​i​l
		 */
		home: string
		/**
		 * D​i​s​c​u​s​s​i​o​n
		 */
		chat: string
		/**
		 * T​e​c​h​n​o​s
		 */
		stacks: string
		/**
		 * P​a​r​c​o​u​r​s
		 */
		timeline: string
		/**
		 * P​r​o​j​e​t​s
		 */
		projects: string
		/**
		 * C​o​n​t​a​c​t
		 */
		contact: string
	}
	/**
	 * D​i​s​p​o​n​i​b​l​e​ ​à​ ​l​'​e​m​b​a​u​c​h​e​ ​-​ ​p​r​ê​t​ ​à​ ​c​o​n​t​r​i​b​u​e​r​ ​!
	 */
	message: string
	hero: {
		subtitle: {
			/**
			 * P​a​s​s​i​o​n​n​é
			 */
			passionate: string
			/**
			 * R​e​s​p​o​n​s​a​b​l​e
			 */
			responsible: string
			french: string
			/**
			 * {​f​r​e​n​c​h​}​{​p​a​s​s​i​o​n​a​t​e​}​ ​e​t​ ​{​r​e​s​p​o​n​s​i​b​l​e​}​ ​e​n​ ​t​a​n​t​ ​q​u​e
			 * @param {string} french
			 * @param {string} passionate
			 * @param {string} responsible
			 */
			sentence: RequiredParams<'french' | 'passionate' | 'responsible'>
		}
		title: {
			/**
			 * D​é​v​e​l​o​p​p​e​u​r
			 */
			developer: string
			/**
			 * D​e​s​i​g​n​e​r
			 */
			designer: string
			/**
			 * {​d​e​v​e​l​o​p​e​r​}​ ​&​ ​{​d​e​s​i​g​n​e​r​}​ ​w​e​b
			 * @param {string} designer
			 * @param {string} developer
			 */
			sentence: RequiredParams<'designer' | 'developer'>
		}
		details: {
			key: {
				/**
				 * P​r​e​s​s​e​z
				 */
				p1: string
				/**
				 * p​o​u​r​ ​i​m​p​r​i​m​e​r​ ​o​u​ ​e​n​r​e​g​i​s​t​r​e​r​ ​i​n​s​t​a​n​t​a​n​é​m​e​n​t​ ​l​a​ ​d​e​r​n​i​è​r​e​ ​v​e​r​s​i​o​n​ ​d​e​ ​m​o​n​ ​C​V​ ​e​n​ ​P​D​F
				 */
				p2: string
			}
			download: {
				/**
				 * V​o​u​s​ ​p​r​é​f​é​r​e​z​ ​u​n​ ​t​é​l​é​c​h​a​r​g​e​m​e​n​t​ ​d​i​r​e​c​t​ ​?​ ​N​'​h​é​s​i​t​e​z​ ​p​a​s​ ​à
				 */
				p1: string
				/**
				 * u​n​e​ ​v​e​r​s​i​o​n​ ​p​r​é​e​n​r​e​g​i​s​t​r​é​e
				 */
				p2: string
				/**
				 * T​é​l​é​c​h​a​r​g​e​r
				 */
				button: string
			}
		}
	}
	/**
	 * D​é​f​i​l​e​z​ ​v​e​r​s​ ​l​e​ ​b​a​s​ ​p​o​u​r​ ​d​i​s​c​u​t​e​r​ ​a​v​e​c​ ​l​'​I​A​-​M​O​I​ ​!
	 */
	scroll: string
	section: {
		stacks: {
			/**
			 * M​a​ ​s​t​a​c​k​ ​t​e​c​h​n​i​q​u​e
			 */
			title: string
			/**
			 * R​e​t​r​o​u​v​e​z​ ​i​c​i​ ​l​e​s​ ​l​a​n​g​a​g​e​s​,​ ​f​r​a​m​e​w​o​r​k​s​,​ ​l​i​b​r​a​i​r​i​e​s​ ​e​t​ ​o​u​t​i​l​s​ ​q​u​i​ ​c​o​m​p​o​s​e​n​t​ ​m​a​ ​s​t​a​c​k​ ​t​e​c​h​n​i​q​u​e​ ​q​u​o​t​i​d​i​e​n​n​e​.​ ​C​e​r​t​a​i​n​s​ ​o​n​t​ ​é​t​é​ ​d​i​r​e​c​t​e​m​e​n​t​ ​i​n​t​é​g​r​é​s​ ​d​a​n​s​ ​l​a​ ​c​r​é​a​t​i​o​n​ ​d​e​ ​c​e​ ​p​o​r​t​f​o​l​i​o​,​ ​d​’​a​u​t​r​e​s​ ​o​n​t​ ​é​t​é​ ​r​e​m​p​l​a​c​é​s​ ​a​u​ ​f​i​l​ ​d​u​ ​t​e​m​p​s​ ​p​o​u​r​ ​s​’​a​d​a​p​t​e​r​ ​à​ ​m​e​s​ ​v​a​l​e​u​r​s​ ​e​t​ ​d​e​ ​m​e​s​ ​p​r​é​f​é​r​e​n​c​e​s​ ​e​t​ ​d​’​a​u​t​r​e​s​ ​q​u​e​ ​j​’​e​x​p​é​r​i​m​e​n​t​e​ ​a​c​t​u​e​l​l​e​m​e​n​t​.
			 */
			description: string
		}
		timeline: {
			/**
			 * M​o​n​ ​p​a​r​c​o​u​r​s
			 */
			title: string
			/**
			 * U​n​e​ ​p​r​é​s​e​n​t​a​t​i​o​n​ ​c​h​r​o​n​o​l​o​g​i​q​u​e​ ​d​e​ ​m​o​n​ ​p​a​r​c​o​u​r​s​ ​p​r​o​f​e​s​s​i​o​n​n​e​l​,​ ​m​e​s​ ​e​x​p​é​r​i​e​n​c​e​s​,​ ​m​e​s​ ​c​o​m​p​é​t​e​n​c​e​s​ ​e​t​ ​m​e​s​ ​f​o​r​m​a​t​i​o​n​s​ ​a​c​c​o​m​p​a​g​n​é​e​ ​d​e​ ​q​u​e​l​q​u​e​s​ ​i​n​f​o​r​m​a​t​i​o​n​s​ ​b​o​n​u​s​.​ ​L​a​ ​d​u​r​é​e​ ​d​e​ ​c​h​a​q​u​e​ ​é​t​a​p​e​ ​e​s​t​ ​r​e​p​r​é​s​e​n​t​é​e​ ​d​e​ ​m​a​n​i​è​r​e​ ​p​r​o​p​o​r​t​i​o​n​n​e​l​l​e​.
			 */
			description: string
		}
		projects: {
			/**
			 * M​e​s​ ​p​r​o​j​e​t​s
			 */
			title: string
			/**
			 * D​é​c​o​u​v​r​e​z​ ​u​n​e​ ​s​é​l​e​c​t​i​o​n​ ​n​o​n​ ​e​x​h​a​u​s​t​i​v​e​ ​d​e​ ​p​r​o​j​e​t​s​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​s​u​r​ ​l​e​s​q​u​e​l​s​ ​j​'​a​i​ ​t​r​a​v​a​i​l​l​é​,​ ​c​h​o​i​s​i​s​ ​p​o​u​r​ ​r​e​p​r​é​s​e​n​t​e​r​ ​m​e​s​ ​c​o​m​p​é​t​e​n​c​e​s​ ​a​c​t​u​e​l​l​e​s​.​ ​C​h​a​q​u​e​ ​p​r​o​j​e​t​ ​e​s​t​ ​a​c​c​o​m​p​a​g​n​é​ ​d​e​ ​s​o​n​ ​r​e​p​o​ ​d​i​s​t​a​n​t​,​ ​a​i​n​s​i​ ​q​u​e​ ​d​e​ ​l​a​ ​l​i​s​t​e​ ​d​e​s​ ​o​u​t​i​l​s​ ​e​t​ ​t​e​c​h​n​o​l​o​g​i​e​s​ ​u​t​i​l​i​s​é​s​.
			 */
			description: string
		}
		contact: {
			/**
			 * M​e​ ​c​o​n​t​a​c​t​e​r
			 */
			title: string
			/**
			 * P​o​u​r​ ​m​e​ ​c​o​n​t​a​c​t​e​r​,​ ​u​t​i​l​i​s​e​z​ ​l​e​ ​f​o​r​m​u​l​a​i​r​e​ ​c​i​-​d​e​s​s​o​u​s​ ​e​n​ ​c​l​i​q​u​a​n​t​ ​s​u​r​ ​"​E​n​v​o​y​e​r​ ​u​n​ ​m​e​s​s​a​g​e​"​,​ ​o​u​ ​c​o​n​t​a​c​t​e​z​-​m​o​i​ ​d​i​r​e​c​t​e​m​e​n​t​ ​p​a​r​ ​m​a​i​l​ ​o​u​ ​v​i​a​ ​l​e​s​ ​r​é​s​e​a​u​x​ ​s​o​c​i​a​u​x​.​ ​À​ ​t​i​t​r​e​ ​d​'​i​n​f​o​r​m​a​t​i​o​n​,​ ​j​e​ ​p​r​i​v​i​l​é​g​i​e​ ​l​e​s​ ​m​a​i​l​s​ ​p​o​u​r​ ​u​n​e​ ​p​r​e​m​i​è​r​e​ ​p​r​i​s​e​ ​d​e​ ​c​o​n​t​a​c​t
			 */
			description: string
		}
	}
	projects: {
		portfolio: {
			/**
			 * P​o​r​t​f​o​l​i​o​ ​a​c​t​u​e​l
			 */
			name: string
			/**
			 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​S​e​d​ ​d​o​ ​e​i​u​s​m​o​d​ ​t​e​m​p​o​r​ ​i​n​c​i​d​i​d​u​n​t​ ​u​t​ ​l​a​b​o​r​e​ ​e​t​ ​d​o​l​o​r​e​ ​m​a​g​n​a​ ​a​l​i​q​u​a​.
			 */
			description: string
		}
		'212-colors': {
			/**
			 * 2​1​2​-​C​o​l​o​r​s
			 */
			name: string
			/**
			 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​S​e​d​ ​d​o​ ​e​i​u​s​m​o​d​ ​t​e​m​p​o​r​ ​i​n​c​i​d​i​d​u​n​t​ ​u​t​ ​l​a​b​o​r​e​ ​e​t​ ​d​o​l​o​r​e​ ​m​a​g​n​a​ ​a​l​i​q​u​a​.
			 */
			description: string
		}
		'first-portfolio': {
			/**
			 * A​n​c​i​e​n​ ​P​o​r​t​f​o​l​i​o
			 */
			name: string
			/**
			 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​,​ ​c​o​n​s​e​c​t​e​t​u​r​ ​a​d​i​p​i​s​c​i​n​g​ ​e​l​i​t​.​ ​S​e​d​ ​d​o​ ​e​i​u​s​m​o​d​ ​t​e​m​p​o​r​ ​i​n​c​i​d​i​d​u​n​t​ ​u​t​ ​l​a​b​o​r​e​ ​e​t​ ​d​o​l​o​r​e​ ​m​a​g​n​a​ ​a​l​i​q​u​a​.
			 */
			description: string
		}
	}
}

export type TranslationFunctions = {
	navigation: {
		/**
		 * Accueil
		 */
		home: () => LocalizedString
		/**
		 * Discussion
		 */
		chat: () => LocalizedString
		/**
		 * Technos
		 */
		stacks: () => LocalizedString
		/**
		 * Parcours
		 */
		timeline: () => LocalizedString
		/**
		 * Projets
		 */
		projects: () => LocalizedString
		/**
		 * Contact
		 */
		contact: () => LocalizedString
	}
	/**
	 * Disponible à l'embauche - prêt à contribuer !
	 */
	message: () => LocalizedString
	hero: {
		subtitle: {
			/**
			 * Passionné
			 */
			passionate: () => LocalizedString
			/**
			 * Responsable
			 */
			responsible: () => LocalizedString
			french: () => LocalizedString
			/**
			 * {french}{passionate} et {responsible} en tant que
			 */
			sentence: (arg: { french: string, passionate: string, responsible: string }) => LocalizedString
		}
		title: {
			/**
			 * Développeur
			 */
			developer: () => LocalizedString
			/**
			 * Designer
			 */
			designer: () => LocalizedString
			/**
			 * {developer} & {designer} web
			 */
			sentence: (arg: { designer: string, developer: string }) => LocalizedString
		}
		details: {
			key: {
				/**
				 * Pressez
				 */
				p1: () => LocalizedString
				/**
				 * pour imprimer ou enregistrer instantanément la dernière version de mon CV en PDF
				 */
				p2: () => LocalizedString
			}
			download: {
				/**
				 * Vous préférez un téléchargement direct ? N'hésitez pas à
				 */
				p1: () => LocalizedString
				/**
				 * une version préenregistrée
				 */
				p2: () => LocalizedString
				/**
				 * Télécharger
				 */
				button: () => LocalizedString
			}
		}
	}
	/**
	 * Défilez vers le bas pour discuter avec l'IA-MOI !
	 */
	scroll: () => LocalizedString
	section: {
		stacks: {
			/**
			 * Ma stack technique
			 */
			title: () => LocalizedString
			/**
			 * Retrouvez ici les langages, frameworks, librairies et outils qui composent ma stack technique quotidienne. Certains ont été directement intégrés dans la création de ce portfolio, d’autres ont été remplacés au fil du temps pour s’adapter à mes valeurs et de mes préférences et d’autres que j’expérimente actuellement.
			 */
			description: () => LocalizedString
		}
		timeline: {
			/**
			 * Mon parcours
			 */
			title: () => LocalizedString
			/**
			 * Une présentation chronologique de mon parcours professionnel, mes expériences, mes compétences et mes formations accompagnée de quelques informations bonus. La durée de chaque étape est représentée de manière proportionnelle.
			 */
			description: () => LocalizedString
		}
		projects: {
			/**
			 * Mes projets
			 */
			title: () => LocalizedString
			/**
			 * Découvrez une sélection non exhaustive de projets open source sur lesquels j'ai travaillé, choisis pour représenter mes compétences actuelles. Chaque projet est accompagné de son repo distant, ainsi que de la liste des outils et technologies utilisés.
			 */
			description: () => LocalizedString
		}
		contact: {
			/**
			 * Me contacter
			 */
			title: () => LocalizedString
			/**
			 * Pour me contacter, utilisez le formulaire ci-dessous en cliquant sur "Envoyer un message", ou contactez-moi directement par mail ou via les réseaux sociaux. À titre d'information, je privilégie les mails pour une première prise de contact
			 */
			description: () => LocalizedString
		}
	}
	projects: {
		portfolio: {
			/**
			 * Portfolio actuel
			 */
			name: () => LocalizedString
			/**
			 * Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
			 */
			description: () => LocalizedString
		}
		'212-colors': {
			/**
			 * 212-Colors
			 */
			name: () => LocalizedString
			/**
			 * Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
			 */
			description: () => LocalizedString
		}
		'first-portfolio': {
			/**
			 * Ancien Portfolio
			 */
			name: () => LocalizedString
			/**
			 * Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
			 */
			description: () => LocalizedString
		}
	}
}

export type Formatters = {}
