// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	navigation: {
		/**
		 * A​c​c​u​e​i​l
		 */
		home: string
		/**
		 * D​i​s​c​u​s​s​i​o​n
		 */
		chat: string
		/**
		 * T​e​c​h​n​o​s
		 */
		stacks: string
		/**
		 * P​a​r​c​o​u​r​s
		 */
		timeline: string
		/**
		 * P​r​o​j​e​t​s
		 */
		projects: string
		/**
		 * C​o​n​t​a​c​t
		 */
		contact: string
	}
	/**
	 * D​i​s​p​o​n​i​b​l​e​ ​à​ ​l​'​e​m​b​a​u​c​h​e​ ​-​ ​p​r​ê​t​ ​à​ ​c​o​n​t​r​i​b​u​e​r​ ​!
	 */
	message: string
	hero: {
		subtitle: {
			/**
			 * P​a​s​s​i​o​n​n​é
			 */
			passionate: string
			/**
			 * R​e​s​p​o​n​s​a​b​l​e
			 */
			responsible: string
			/**
			 * F​r​a​n​ç​a​i​s
			 */
			french: string
			/**
			 * {​f​r​e​n​c​h​}​ ​–​ ​{​p​a​s​s​i​o​n​a​t​e​}​ ​&​ ​{​r​e​s​p​o​n​s​i​b​l​e​}
			 * @param {string} french
			 * @param {string} passionate
			 * @param {string} responsible
			 */
			sentence: RequiredParams<'french' | 'passionate' | 'responsible'>
		}
		title: {
			/**
			 * D​é​v​e​l​o​p​p​e​u​r
			 */
			developer: string
			/**
			 * D​e​s​i​g​n​e​r
			 */
			designer: string
			/**
			 * {​d​e​v​e​l​o​p​e​r​}​ ​&​ ​{​d​e​s​i​g​n​e​r​}​ ​w​e​b
			 * @param {string} designer
			 * @param {string} developer
			 */
			sentence: RequiredParams<'designer' | 'developer'>
		}
		details: {
			key: {
				/**
				 * P​r​e​s​s​e​z
				 */
				p1: string
				/**
				 * p​o​u​r​ ​i​m​p​r​i​m​e​r​ ​o​u​ ​e​n​r​e​g​i​s​t​r​e​r​ ​i​n​s​t​a​n​t​a​n​é​m​e​n​t​ ​l​a​ ​d​e​r​n​i​è​r​e​ ​v​e​r​s​i​o​n​ ​d​e​ ​m​o​n​ ​C​V​ ​e​n​ ​P​D​F
				 */
				p2: string
			}
			download: {
				/**
				 * V​o​u​s​ ​p​r​é​f​é​r​e​z​ ​u​n​ ​t​é​l​é​c​h​a​r​g​e​m​e​n​t​ ​d​i​r​e​c​t​ ​?​ ​N​'​h​é​s​i​t​e​z​ ​p​a​s​ ​à
				 */
				p1: string
				/**
				 * u​n​e​ ​v​e​r​s​i​o​n​ ​p​r​é​e​n​r​e​g​i​s​t​r​é​e
				 */
				p2: string
				/**
				 * T​é​l​é​c​h​a​r​g​e​r
				 */
				button: string
			}
		}
	}
	/**
	 * D​é​f​i​l​e​z​ ​v​e​r​s​ ​l​e​ ​b​a​s​ ​p​o​u​r​ ​d​i​s​c​u​t​e​r​ ​a​v​e​c​ ​l​'​I​A​-​M​O​I​ ​!
	 */
	scroll: string
}

export type TranslationFunctions = {
	navigation: {
		/**
		 * Accueil
		 */
		home: () => LocalizedString
		/**
		 * Discussion
		 */
		chat: () => LocalizedString
		/**
		 * Technos
		 */
		stacks: () => LocalizedString
		/**
		 * Parcours
		 */
		timeline: () => LocalizedString
		/**
		 * Projets
		 */
		projects: () => LocalizedString
		/**
		 * Contact
		 */
		contact: () => LocalizedString
	}
	/**
	 * Disponible à l'embauche - prêt à contribuer !
	 */
	message: () => LocalizedString
	hero: {
		subtitle: {
			/**
			 * Passionné
			 */
			passionate: () => LocalizedString
			/**
			 * Responsable
			 */
			responsible: () => LocalizedString
			/**
			 * Français
			 */
			french: () => LocalizedString
			/**
			 * {french} – {passionate} & {responsible}
			 */
			sentence: (arg: { french: string, passionate: string, responsible: string }) => LocalizedString
		}
		title: {
			/**
			 * Développeur
			 */
			developer: () => LocalizedString
			/**
			 * Designer
			 */
			designer: () => LocalizedString
			/**
			 * {developer} & {designer} web
			 */
			sentence: (arg: { designer: string, developer: string }) => LocalizedString
		}
		details: {
			key: {
				/**
				 * Pressez
				 */
				p1: () => LocalizedString
				/**
				 * pour imprimer ou enregistrer instantanément la dernière version de mon CV en PDF
				 */
				p2: () => LocalizedString
			}
			download: {
				/**
				 * Vous préférez un téléchargement direct ? N'hésitez pas à
				 */
				p1: () => LocalizedString
				/**
				 * une version préenregistrée
				 */
				p2: () => LocalizedString
				/**
				 * Télécharger
				 */
				button: () => LocalizedString
			}
		}
	}
	/**
	 * Défilez vers le bas pour discuter avec l'IA-MOI !
	 */
	scroll: () => LocalizedString
}

export type Formatters = {}
